import {test,expect} from '@playwright/test';
import {createSingleplayerWorld} from './helpers/world-flow.mjs';

async function key(page,code){await page.evaluate(code=>window.dispatchEvent(new KeyboardEvent('keydown',{code,bubbles:true})),code);}
async function runCommand(page,text){await page.evaluate(()=>window.dispatchEvent(new KeyboardEvent('keydown',{code:'Slash',bubbles:true})));await expect(page.locator('#chat-input-wrap')).not.toHaveClass(/hidden/);await page.locator('#chat-input').fill(text);await page.locator('#chat-input').press('Enter');await expect(page.locator('#chat-input-wrap')).toHaveClass(/hidden/);}

test('Creative inventory exposes categorized searchable registry catalog and writes through the real cursor',async({page})=>{
  await page.goto('/?e2e=1');await createSingleplayerWorld(page,{name:'CI Creative Inventory',seed:'ci-creative-inventory-2026',mode:'creative',prompt:'平原'});await key(page,'KeyE');await expect(page.locator('#inventory')).not.toHaveClass(/hidden/);
  const catalog=page.locator('[data-creative-catalog]'),search=page.locator('.creative-catalog-search'),grid=page.locator('.creative-catalog-grid');await expect(catalog).toBeVisible();await expect(page.locator('#inventory .inventory-top')).toHaveClass(/hidden/);await expect(page.locator('#inventory-grid')).toHaveClass(/hidden/);await expect(page.locator('#inventory-hotbar')).toBeVisible();await expect(page.locator('[data-creative-category]')).toHaveCount(8);expect(await grid.locator('[data-creative-item]').count()).toBeGreaterThan(20);
  await search.fill('wooden pickaxe');await expect(grid.locator('[data-creative-item]')).toHaveCount(1);await expect(grid.locator('[data-creative-item="wooden_pickaxe"]')).toHaveAttribute('title','木镐');await grid.locator('[data-creative-item="wooden_pickaxe"]').click();await expect(page.locator('#cursor-stack')).not.toHaveClass(/hidden/);await expect(page.locator('#cursor-stack .inv-slot')).toHaveAttribute('title','木镐');
  const firstHotbar=page.locator('#inventory-hotbar [data-inv-index="27"]');await expect(firstHotbar).toHaveAttribute('title','草方块');await firstHotbar.click();await expect(page.locator('#inventory-hotbar [data-inv-index="27"]')).toHaveAttribute('title','木镐');await expect(page.locator('#cursor-stack .inv-slot')).toHaveAttribute('title','草方块');
  await search.fill('');await page.locator('[data-creative-category="combat"]').click();await expect(page.locator('[data-creative-category="combat"]')).toHaveClass(/active/);await expect(grid.locator('[data-creative-item="iron_sword"]')).toBeVisible();await expect(grid.locator('[data-creative-item="block:1"]')).toHaveCount(0);
  await key(page,'Escape');await expect(page.locator('#inventory')).toHaveClass(/hidden/);await runCommand(page,'/gamemode survival');await key(page,'KeyE');await expect(page.locator('#inventory')).not.toHaveClass(/hidden/);await expect(catalog).toHaveClass(/hidden/);await expect(page.locator('#inventory .inventory-top')).not.toHaveClass(/hidden/);await expect(page.locator('#inventory-grid')).not.toHaveClass(/hidden/);await expect(page.locator('#inventory-hotbar [data-inv-index="27"]')).toHaveAttribute('title','木镐');
});
