import {test,expect} from '@playwright/test';
import {BLOCK} from '../../src/blocks.js';
import {HOTBAR_START} from '../../src/inventory-layout.js';
import {PLAYER_EYE_HEIGHT} from '../../src/player-environment-rules.js';
import {createAuthoritativeServerRuntime} from '../../server/runtime.mjs';

const ORIGIN='http://127.0.0.1:4173';
async function lockPointerAndSetView(page,yaw,pitch=0){const canvas=page.locator('#game-canvas');await canvas.click({position:{x:8,y:8}});await expect.poll(()=>page.evaluate(()=>document.pointerLockElement?.id||null),{timeout:5_000}).toBe('game-canvas');await page.evaluate(({yaw,pitch})=>globalThis.__minecraftE2E?.setLook(yaw,pitch),{yaw,pitch});}

test('survival browser secondary places on server, consumes one item, and failed placement consumes nothing',async({page})=>{
  let tick=null;const runtime=createAuthoritativeServerRuntime({config:{host:'127.0.0.1',port:0,allowedOrigins:[ORIGIN],worldId:'e2e-survival-placement',seed:'survival-placement-e2e-seed',prompt:'plains',mode:'survival',spawnX:0,spawnZ:0,prefetchRadius:0,terrainCacheChunks:32},setIntervalFn:callback=>(tick=callback,{timer:'manual-survival-placement'}),clearIntervalFn:()=>{}});
  try{
    const address=await runtime.start(),url=`ws://127.0.0.1:${address.port}/ws`;await page.goto('/?e2e=1');await page.getByRole('button',{name:'多人游戏'}).click();await page.locator('#multiplayer-url').fill(url);await page.locator('#multiplayer-insecure').check();await page.getByRole('button',{name:'连接服务器'}).click();await expect(page.locator('#loading')).toHaveClass(/hidden/,{timeout:30_000});await expect(page.locator('#hud')).not.toHaveClass(/hidden/);await expect.poll(()=>page.evaluate(()=>globalThis.__minecraftE2E?.multiplayer?.()),{timeout:30_000}).toMatchObject({sessionKind:'multiplayer',state:'ready',ready:true,worldId:'e2e-survival-placement'});
    const [session]=[...runtime.authoritative.sessions];expect(session).toBeTruthy();await lockPointerAndSetView(page,0,0);tick();await expect.poll(()=>runtime.authoritative.snapshot(session)?.tick,{timeout:5_000}).toBe(1);
    const player=runtime.authoritative.snapshot(session);runtime.spawnItemEntity('block:2',2,{x:player.position.x,y:player.position.y+.8,z:player.position.z},{pickupDelay:0,velocity:{x:0,y:0,z:0}});await expect.poll(()=>page.evaluate(()=>globalThis.__minecraftE2E?.itemEntities?.().length),{timeout:5_000}).toBe(1);tick();await expect.poll(()=>page.evaluate(()=>globalThis.__minecraftE2E?.inventoryRevision?.()),{timeout:5_000}).toBe(1);await expect.poll(()=>page.evaluate(index=>globalThis.__minecraftE2E?.inventorySlot?.(index),HOTBAR_START),{timeout:5_000}).toMatchObject({id:'block:2',count:2});await expect.poll(()=>page.evaluate(()=>globalThis.__minecraftE2E?.itemEntities?.().length),{timeout:5_000}).toBe(0);
    const snapshot=runtime.authoritative.snapshot(session),x=Math.floor(snapshot.position.x),y=Math.floor(snapshot.position.y+PLAYER_EYE_HEIGHT),anchorZ=Math.floor(snapshot.position.z)-2,placeZ=anchorZ+1;runtime.setBlock(x,y,placeZ,BLOCK.AIR);runtime.setBlock(x,y,anchorZ,BLOCK.STONE);await expect.poll(()=>page.evaluate(({x,y,z})=>globalThis.__minecraftE2E?.worldBlock(x,y,z),{x,y,z:anchorZ}),{timeout:5_000}).toBe(BLOCK.STONE);await expect.poll(()=>page.evaluate(({x,y,z})=>globalThis.__minecraftE2E?.worldBlock(x,y,z),{x,y,z:placeZ}),{timeout:5_000}).toBe(BLOCK.AIR);
    const worldBefore=runtime.world.revision,inventoryBefore=runtime.inventories.snapshot(session).revision;await page.mouse.down({button:'right'});await page.mouse.up({button:'right'});await expect.poll(()=>runtime.server.getSessionInputState(session)?.pendingActionCount,{timeout:5_000}).toBe(2);await expect(page.locator('#toast')).not.toContainText('联机方块/战斗权威尚未接入');tick();await expect.poll(()=>runtime.world.getBlock(x,y,placeZ),{timeout:5_000}).toBe(BLOCK.DIRT);await expect.poll(()=>page.evaluate(({x,y,z})=>globalThis.__minecraftE2E?.worldBlock(x,y,z),{x,y,z:placeZ}),{timeout:5_000}).toBe(BLOCK.DIRT);await expect.poll(()=>page.evaluate(()=>globalThis.__minecraftE2E?.inventoryRevision?.()),{timeout:5_000}).toBe(inventoryBefore+1);await expect.poll(()=>page.evaluate(index=>globalThis.__minecraftE2E?.inventorySlot?.(index),HOTBAR_START),{timeout:5_000}).toMatchObject({id:'block:2',count:1});expect(runtime.world.revision).toBe(worldBefore+1);
    const stableWorld=runtime.world.revision,stableInventory=runtime.inventories.snapshot(session).revision;await page.mouse.down({button:'right'});await page.mouse.up({button:'right'});await expect.poll(()=>runtime.server.getSessionInputState(session)?.pendingActionCount,{timeout:5_000}).toBe(2);tick();expect(runtime.world.revision).toBe(stableWorld);expect(runtime.inventories.snapshot(session).revision).toBe(stableInventory);await expect.poll(()=>page.evaluate(index=>globalThis.__minecraftE2E?.inventorySlot?.(index),HOTBAR_START),{timeout:5_000}).toMatchObject({id:'block:2',count:1});
  }finally{await runtime.stop();}
});
