import {test,expect} from '@playwright/test';
import {createAuthoritativeServerRuntime} from '../../server/runtime.mjs';

const ORIGIN='http://127.0.0.1:4173';
async function connectPage(page,url,worldId){await page.goto('/?e2e=1');await page.getByRole('button',{name:'多人游戏'}).click();await page.locator('#multiplayer-url').fill(url);await page.locator('#multiplayer-insecure').check();await page.getByRole('button',{name:'连接服务器'}).click();await expect(page.locator('#loading')).toHaveClass(/hidden/,{timeout:30_000});await expect.poll(()=>page.evaluate(()=>globalThis.__minecraftE2E?.multiplayer?.()),{timeout:30_000}).toMatchObject({sessionKind:'multiplayer',state:'ready',ready:true,worldId});await expect.poll(()=>page.evaluate(()=>globalThis.__minecraftE2E?.combat?.()),{timeout:10_000}).toMatchObject({revision:0,hp:20,maxHp:20,dead:false});}

test('two browser players use server-authoritative PvP death drops and respawn',async({browser})=>{
  const errors=[],runtime=createAuthoritativeServerRuntime({config:{host:'127.0.0.1',port:0,allowedOrigins:[ORIGIN],worldId:'e2e-pvp-combat',seed:'pvp-combat-seed',prompt:'plains',mode:'survival',spawnX:0,spawnZ:0,prefetchRadius:0,terrainCacheChunks:32},combatOptions:{attackCooldownMs:0,hurtCooldownMs:0},onError:event=>errors.push(event)});let contextA=null,contextB=null;
  try{
    const address=await runtime.start(),url=`ws://127.0.0.1:${address.port}/ws`;contextA=await browser.newContext();contextB=await browser.newContext();const pageA=await contextA.newPage(),pageB=await contextB.newPage();await connectPage(pageA,url,'e2e-pvp-combat');await connectPage(pageB,url,'e2e-pvp-combat');const sessions=[...runtime.authoritative.sessions];expect(sessions).toHaveLength(2);const [sessionA,sessionB]=sessions,base=runtime.authoritative.snapshot(sessionA).position,y=base.y;
    const align=()=>{runtime.authoritative.simulation.relocate(sessionA,{x:base.x,y,z:base.z},{velocity:{x:0,y:0,z:0}});runtime.authoritative.simulation.relocate(sessionB,{x:base.x,y,z:base.z-2.4},{velocity:{x:0,y:0,z:0}});};align();await expect.poll(()=>runtime.authoritative.snapshot(sessionB).position.z,{timeout:5_000}).toBeCloseTo(base.z-2.4,4);

    await pageA.evaluate(()=>globalThis.__minecraftE2E?.sendAttack?.({yaw:0,pitch:0}));await expect.poll(()=>pageB.evaluate(()=>globalThis.__minecraftE2E?.combat?.()),{timeout:5_000}).toMatchObject({revision:1,hp:19,dead:false});await expect.poll(()=>runtime.authoritative.snapshot(sessionB).velocity.z,{timeout:5_000}).toBeLessThan(0);

    const given=runtime.addInventoryItem(sessionB,'block:6',3);expect(given.changed).toBe(true);await expect.poll(()=>pageB.evaluate(()=>Array.from({length:36},(_,i)=>globalThis.__minecraftE2E?.inventorySlot?.(i)).find(stack=>stack?.id==='block:6')||null),{timeout:5_000}).toEqual({id:'block:6',count:3});align();runtime.setPlayerMode(sessionA,'creative');const deathPosition={...runtime.authoritative.snapshot(sessionB).position};await pageA.evaluate(()=>globalThis.__minecraftE2E?.sendAttack?.({yaw:0,pitch:0}));
    await expect.poll(()=>pageB.evaluate(()=>globalThis.__minecraftE2E?.combat?.()),{timeout:5_000}).toMatchObject({revision:2,hp:0,dead:true});await expect(pageB.locator('#death-menu')).toHaveClass(/active/);await expect(pageB.locator('#hearts .heart.empty')).toHaveCount(10);await expect(pageB.locator('#death-detail')).toContainText('服务器已结算死亡与掉落');expect(runtime.combats.isDead(sessionB)).toBe(true);expect(runtime.inventories.snapshot(sessionB).slots.every(stack=>stack===null)).toBe(true);await expect.poll(()=>runtime.itemEntities.size,{timeout:5_000}).toBeGreaterThan(0);await expect.poll(()=>pageB.evaluate(()=>globalThis.__minecraftE2E?.itemEntities?.().length||0),{timeout:5_000}).toBeGreaterThan(0);

    await pageB.keyboard.press('Escape');await expect(pageB.locator('#death-menu')).toHaveClass(/active/);await expect(pageB.locator('#pause-menu')).not.toHaveClass(/active/);
    await pageB.locator('#death-menu [data-action="respawn"]').click();await expect.poll(()=>pageB.evaluate(()=>globalThis.__minecraftE2E?.combat?.()),{timeout:5_000}).toMatchObject({revision:3,hp:20,dead:false});await expect(pageB.locator('#death-menu')).not.toHaveClass(/active/,{timeout:5_000});await expect(pageB.locator('#hearts .heart.empty')).toHaveCount(0);const respawned=runtime.authoritative.snapshot(sessionB).position;expect(Math.hypot(respawned.x-deathPosition.x,respawned.z-deathPosition.z)).toBeGreaterThan(.5);expect(errors).toEqual([]);
  }finally{await contextA?.close();await contextB?.close();if(runtime.state!=='stopped')await runtime.stop();}
});
