import {createServer} from 'node:http';
import {randomUUID} from 'node:crypto';
import {WebSocketServer} from 'ws';
import {ClientInputSessionGate,assertClientSessionId} from '../src/client-input-envelope.js';
import {NetworkSequenceGate,nextNetworkSequence} from '../src/network-sequence.js';
import {MULTIPLAYER_SUBPROTOCOL,decodeClientHello,encodeServerWelcome} from '../src/multiplayer-handshake.js';
import {MULTIPLAYER_COMMAND_REQUEST_KIND,decodeMultiplayerCommandRequest,encodeMultiplayerCommandResult} from '../src/multiplayer-command-wire.js';
import {MULTIPLAYER_CHAT_SEND_KIND,decodeMultiplayerChatSend,encodeMultiplayerChatMessage} from '../src/multiplayer-chat-wire.js';
import {INVENTORY_TRANSACTION_REQUEST_KIND,decodeInventoryTransactionRequest,encodeInventoryTransactionResult} from '../src/inventory-transaction-wire.js';
import {EQUIPMENT_TRANSACTION_REQUEST_KIND,decodeEquipmentTransactionRequest,encodeEquipmentTransactionResult} from '../src/equipment-transaction-wire.js';
import {encodeServerInventorySnapshot} from '../src/server-inventory-snapshot.js';
import {encodeServerEquipmentSnapshot} from '../src/server-equipment-snapshot.js';
import {encodeServerPlayerSnapshot} from '../src/server-player-snapshot.js';
import {encodeServerWorldInfo} from '../src/server-world-info.js';
import {encodeRemotePlayerSpawn,encodeRemotePlayerSnapshot,encodeRemotePlayerDespawn} from '../src/remote-player-replication.js';
import {encodeItemEntitySpawn,encodeItemEntitySnapshot,encodeItemEntityDespawn} from '../src/item-entity-replication.js';
import {encodeMiningProgress} from '../src/mining-progress-replication.js';
import {encodeWorldEditSync,encodeWorldBlockChange} from '../src/world-edit-replication.js';
import {ServerPlayerInputState} from './player-input-state.mjs';

export const DEFAULT_MULTIPLAYER_HOST='127.0.0.1';
export const DEFAULT_MULTIPLAYER_PORT=0;
export const DEFAULT_MULTIPLAYER_PATH='/ws';
export const DEFAULT_MAX_PAYLOAD=16*1024;
export const DEFAULT_SERVER_HELLO_TIMEOUT_MS=5000;
export const SERVER_HELLO_TIMEOUT_CLOSE_CODE=4001;
export const DEFAULT_ALLOWED_ORIGINS=Object.freeze(['http://localhost:4173','http://127.0.0.1:4173']);
export const DEFAULT_CHAT_RATE_LIMIT=8;
export const DEFAULT_CHAT_RATE_WINDOW_MS=5000;

function assertPositiveInteger(value,label,{min=1,max=Number.MAX_SAFE_INTEGER}={}){if(!Number.isInteger(value)||value<min||value>max)throw new RangeError(`${label} must be an integer from ${min} to ${max}`);return value;}
function assertPath(value){if(typeof value!=='string'||!value.startsWith('/')||value.includes('?')||value.includes('#'))throw new RangeError('websocket path must be an absolute path without query or fragment');return value;}
function normalizeOrigin(value){if(typeof value!=='string'||!value)throw new RangeError('allowed origin must be a non-empty absolute origin');let url;try{url=new URL(value);}catch{throw new RangeError(`invalid allowed origin: ${value}`);}if(url.origin==='null'||url.username||url.password)throw new RangeError(`invalid allowed origin: ${value}`);return url.origin;}
function normalizeAllowedOrigins(value){if(value==='*')return{allowAny:true,origins:new Set()};if(!value||typeof value[Symbol.iterator]!=='function'||typeof value==='string')throw new TypeError('allowedOrigins must be an iterable of origins or "*"');const origins=new Set();for(const origin of value)origins.add(normalizeOrigin(origin));if(!origins.size)throw new RangeError('allowedOrigins must not be empty');return{allowAny:false,origins};}
function originAllowed(origin,policy,allowMissingOrigin){if(origin===undefined)return!!allowMissingOrigin;let normalized;try{normalized=normalizeOrigin(origin);}catch{return false;}return policy.allowAny||policy.origins.has(normalized);}
function offeredProtocols(header){if(typeof header!=='string')return[];return header.split(',').map(value=>value.trim()).filter(Boolean);}
function rejectUpgrade(socket,statusCode,statusText,extraHeaders=[]){const body=`${statusCode} ${statusText}\n`,headers=[`HTTP/1.1 ${statusCode} ${statusText}`,'Connection: close','Content-Type: text/plain; charset=utf-8',`Content-Length: ${Buffer.byteLength(body)}`,...extraHeaders,'',''];try{socket.end(headers.join('\r\n')+body);}catch{socket.destroy();}}
function parseJsonText(data){let value;try{value=JSON.parse(data);}catch{throw new RangeError('websocket message must contain valid JSON');}if(!value||typeof value!=='object'||Array.isArray(value))throw new TypeError('websocket message must contain a JSON object');return value;}
function defaultSessionFactory(){return `s:${randomUUID()}`;}
function acceptChatRate(state,limit,windowMs,now){const current=now();if(typeof current!=='number'||!Number.isFinite(current))throw new TypeError('chat rate clock must return a finite number');state.chatTimes=state.chatTimes.filter(value=>current-value<windowMs);if(state.chatTimes.length>=limit)return false;state.chatTimes.push(current);return true;}

export function createMultiplayerServer({host=DEFAULT_MULTIPLAYER_HOST,port=DEFAULT_MULTIPLAYER_PORT,path=DEFAULT_MULTIPLAYER_PATH,allowedOrigins=DEFAULT_ALLOWED_ORIGINS,allowMissingOrigin=false,maxPayload=DEFAULT_MAX_PAYLOAD,helloTimeoutMs=DEFAULT_SERVER_HELLO_TIMEOUT_MS,chatRateLimit=DEFAULT_CHAT_RATE_LIMIT,chatRateWindowMs=DEFAULT_CHAT_RATE_WINDOW_MS,now=Date.now,sessionFactory=defaultSessionFactory,playerInputOptions={},onSessionReady=()=>{},onInput=()=>{},onCommand=()=>{},onChat=()=>{},onInventoryTransaction=()=>{},onEquipmentTransaction=()=>{},onSessionClose=()=>{},onSocketError=()=>{}}={}){
  if(typeof host!=='string'||!host)throw new TypeError('host must be a non-empty string');if(!Number.isInteger(port)||port<0||port>65535)throw new RangeError('port must be an integer from 0 to 65535');path=assertPath(path);const originPolicy=normalizeAllowedOrigins(allowedOrigins);maxPayload=assertPositiveInteger(maxPayload,'maxPayload',{min:1024,max:1024*1024});helloTimeoutMs=assertPositiveInteger(helloTimeoutMs,'helloTimeoutMs',{min:250,max:60000});chatRateLimit=assertPositiveInteger(chatRateLimit,'chatRateLimit',{min:1,max:100});chatRateWindowMs=assertPositiveInteger(chatRateWindowMs,'chatRateWindowMs',{min:250,max:60000});if(typeof now!=='function')throw new TypeError('now must be a function');if(typeof sessionFactory!=='function')throw new TypeError('sessionFactory must be a function');if(!playerInputOptions||typeof playerInputOptions!=='object'||Array.isArray(playerInputOptions))throw new TypeError('playerInputOptions must be an object');for(const [name,callback] of Object.entries({onSessionReady,onInput,onCommand,onChat,onInventoryTransaction,onEquipmentTransaction,onSessionClose,onSocketError}))if(typeof callback!=='function')throw new TypeError(`${name} must be a function`);
  const reportSocketError=(session,error)=>{try{onSocketError({session,error});}catch{}},sessions=new Map();let chatMessageSeq=0;
  const httpServer=createServer((request,response)=>{if(request.method==='GET'&&request.url==='/healthz'){const body=JSON.stringify({ok:true,protocol:MULTIPLAYER_SUBPROTOCOL});response.writeHead(200,{'content-type':'application/json; charset=utf-8','content-length':Buffer.byteLength(body),'cache-control':'no-store'});response.end(body);return;}response.writeHead(404,{'content-type':'text/plain; charset=utf-8','cache-control':'no-store'});response.end('Not Found\n');});
  const wss=new WebSocketServer({noServer:true,perMessageDeflate:false,maxPayload,handleProtocols:protocols=>protocols.has(MULTIPLAYER_SUBPROTOCOL)?MULTIPLAYER_SUBPROTOCOL:false});
  httpServer.on('upgrade',(request,socket,head)=>{let pathname;try{pathname=new URL(request.url||'/',`http://${request.headers.host||'localhost'}`).pathname;}catch{rejectUpgrade(socket,400,'Bad Request');return;}if(pathname!==path){rejectUpgrade(socket,404,'Not Found');return;}if(!originAllowed(request.headers.origin,originPolicy,allowMissingOrigin)){rejectUpgrade(socket,403,'Forbidden');return;}if(!offeredProtocols(request.headers['sec-websocket-protocol']).includes(MULTIPLAYER_SUBPROTOCOL)){rejectUpgrade(socket,426,'Upgrade Required',[`Sec-WebSocket-Protocol: ${MULTIPLAYER_SUBPROTOCOL}`]);return;}wss.handleUpgrade(request,socket,head,websocket=>wss.emit('connection',websocket,request));});
  wss.on('connection',(websocket,request)=>{
    const state={phase:'await-hello',session:null,gate:null,commandGate:null,chatGate:null,inventoryTransactionGate:null,equipmentTransactionGate:null,chatTimes:[],inputState:null,helloTimer:null,origin:request.headers.origin||null};state.helloTimer=setTimeout(()=>{state.helloTimer=null;if(state.phase==='await-hello')websocket.close(SERVER_HELLO_TIMEOUT_CLOSE_CODE,'hello timeout');},helloTimeoutMs);
    websocket.on('message',(data,isBinary)=>{if(state.phase==='closed')return;if(isBinary){websocket.close(1003,'binary messages are not supported');return;}let message;try{message=parseJsonText(data.toString('utf8'));}catch{websocket.close(1002,'invalid json message');return;}
      if(state.phase==='await-hello'){try{decodeClientHello(message);}catch{websocket.close(1002,'invalid client hello');return;}clearTimeout(state.helloTimer);state.helloTimer=null;let session,inputState;try{session=assertClientSessionId(sessionFactory());if(sessions.has(session))throw new Error(`duplicate active session id: ${session}`);inputState=new ServerPlayerInputState(session,playerInputOptions);}catch(error){reportSocketError(null,error);websocket.close(1011,'session allocation failed');return;}state.session=session;state.gate=new ClientInputSessionGate(session);state.commandGate=new NetworkSequenceGate();state.chatGate=new NetworkSequenceGate();state.inventoryTransactionGate=new NetworkSequenceGate();state.equipmentTransactionGate=new NetworkSequenceGate();state.inputState=inputState;state.phase='ready';sessions.set(session,{websocket,inputState});websocket.send(JSON.stringify(encodeServerWelcome(session)));try{onSessionReady({session,origin:state.origin,remoteAddress:request.socket.remoteAddress||null,inputState:inputState.snapshot()});}catch(error){reportSocketError(session,error);websocket.close(1011,'session ready handler failed');}return;}
      if(message.kind===MULTIPLAYER_COMMAND_REQUEST_KIND){let command;try{command=decodeMultiplayerCommandRequest(message,{expectedSession:state.session});}catch{websocket.close(1002,'invalid command request');return;}if(!state.commandGate.accept(command.requestId)){websocket.close(1008,'stale or duplicate command request');return;}try{onCommand({session:state.session,command});}catch(error){reportSocketError(state.session,error);websocket.close(1011,'command handler failed');}return;}
      if(message.kind===MULTIPLAYER_CHAT_SEND_KIND){let chat;try{chat=decodeMultiplayerChatSend(message,{expectedSession:state.session});}catch{websocket.close(1002,'invalid chat send');return;}if(!state.chatGate.accept(chat.clientSeq)){websocket.close(1008,'stale or duplicate chat send');return;}let accepted;try{accepted=acceptChatRate(state,chatRateLimit,chatRateWindowMs,now);}catch(error){reportSocketError(state.session,error);websocket.close(1011,'chat rate limiter failed');return;}if(!accepted){websocket.close(1008,'chat rate limit exceeded');return;}try{onChat({session:state.session,chat});}catch(error){reportSocketError(state.session,error);websocket.close(1011,'chat handler failed');}return;}
      if(message.kind===INVENTORY_TRANSACTION_REQUEST_KIND){let transaction;try{transaction=decodeInventoryTransactionRequest(message,{expectedSession:state.session});}catch{websocket.close(1002,'invalid inventory transaction request');return;}if(!state.inventoryTransactionGate.accept(transaction.requestId)){websocket.close(1008,'stale or duplicate inventory transaction request');return;}try{onInventoryTransaction({session:state.session,transaction});}catch(error){reportSocketError(state.session,error);websocket.close(1011,'inventory transaction handler failed');}return;}
      if(message.kind===EQUIPMENT_TRANSACTION_REQUEST_KIND){let transaction;try{transaction=decodeEquipmentTransactionRequest(message,{expectedSession:state.session});}catch{websocket.close(1002,'invalid equipment transaction request');return;}if(!state.equipmentTransactionGate.accept(transaction.requestId)){websocket.close(1008,'stale or duplicate equipment transaction request');return;}try{onEquipmentTransaction({session:state.session,transaction});}catch(error){reportSocketError(state.session,error);websocket.close(1011,'equipment transaction handler failed');}return;}
      let result;try{result=state.gate.accept(message);}catch{websocket.close(1002,'invalid client input envelope');return;}if(!result.accepted){websocket.close(1008,'stale or duplicate packet');return;}let application;try{application=state.inputState.apply(result.message);}catch(error){reportSocketError(state.session,error);websocket.close(1011,'input state failure');return;}if(!application.accepted){websocket.close(1008,application.reason);return;}try{onInput({session:state.session,message:result.message,application,inputState:state.inputState.snapshot()});}catch(error){reportSocketError(state.session,error);websocket.close(1011,'input handler failed');}});
    websocket.on('error',error=>reportSocketError(state.session,error));websocket.on('close',(code,reason)=>{if(state.helloTimer!==null){clearTimeout(state.helloTimer);state.helloTimer=null;}state.phase='closed';if(state.session&&sessions.get(state.session)?.websocket===websocket)sessions.delete(state.session);try{onSessionClose({session:state.session,code,reason:reason.toString('utf8')});}catch(error){reportSocketError(state.session,error);}});
  });
  const sendEncoded=(session,wire)=>{session=assertClientSessionId(session);const entry=sessions.get(session);if(!entry||entry.websocket.readyState!==1)return null;entry.websocket.send(JSON.stringify(wire));return wire;};
  return{httpServer,wss,path,
    async listen(){if(httpServer.listening)return httpServer.address();return new Promise((resolve,reject)=>{const onError=error=>{httpServer.off('listening',onListening);reject(error);},onListening=()=>{httpServer.off('error',onError);resolve(httpServer.address());};httpServer.once('error',onError);httpServer.once('listening',onListening);httpServer.listen(port,host);});},
    address(){return httpServer.address();},get sessionCount(){return sessions.size;},getSessionInputState(session){const entry=sessions.get(assertClientSessionId(session));return entry?entry.inputState.snapshot():null;},drainSessionActions(session,limit){const entry=sessions.get(assertClientSessionId(session));return entry?entry.inputState.drainActions(limit):[];},
    sendCommandResult(session,result){session=assertClientSessionId(session);if(!result||result.session!==session)throw new RangeError('command result session must match target session');return sendEncoded(session,encodeMultiplayerCommandResult(result));},
    sendInventoryTransactionResult(session,result){session=assertClientSessionId(session);if(!result||result.session!==session)throw new RangeError('inventory transaction result session must match target session');return sendEncoded(session,encodeInventoryTransactionResult(result));},
    sendEquipmentTransactionResult(session,result){session=assertClientSessionId(session);if(!result||result.session!==session)throw new RangeError('equipment transaction result session must match target session');return sendEncoded(session,encodeEquipmentTransactionResult(result));},
    broadcastChatMessage(sender,text){sender=assertClientSessionId(sender);if(!sessions.has(sender))throw new Error(`unknown chat sender session: ${sender}`);const wire=encodeMultiplayerChatMessage({messageSeq:chatMessageSeq,sender,text});chatMessageSeq=nextNetworkSequence(chatMessageSeq);let delivered=0,failed=0;for(const session of sessions.keys()){if(sendEncoded(session,wire)===null)failed++;else delivered++;}return Object.freeze({wire,delivered,failed});},
    sendWorldInfo(session,info){session=assertClientSessionId(session);if(!info||info.session!==session)throw new RangeError('world info session must match target session');return sendEncoded(session,encodeServerWorldInfo(info));},
    sendWorldEditSync(session,{worldId,revision,edits}){session=assertClientSessionId(session);const wires=encodeWorldEditSync({session,worldId,revision,edits});for(const wire of wires)if(sendEncoded(session,wire)===null)return null;return wires;},
    sendWorldBlockChange(session,{worldId,revision,x,y,z,previous,id}){session=assertClientSessionId(session);return sendEncoded(session,encodeWorldBlockChange({session,worldId,revision,x,y,z,previous,id}));},
    sendInventorySnapshot(session,snapshot){session=assertClientSessionId(session);if(!snapshot||snapshot.session!==session)throw new RangeError('inventory snapshot session must match target session');return sendEncoded(session,encodeServerInventorySnapshot(snapshot));},
    sendEquipmentSnapshot(session,snapshot){session=assertClientSessionId(session);if(!snapshot||snapshot.session!==session)throw new RangeError('equipment snapshot session must match target session');return sendEncoded(session,encodeServerEquipmentSnapshot(snapshot));},
    sendPlayerSnapshot(session,snapshot){session=assertClientSessionId(session);if(!snapshot||snapshot.session!==session)throw new RangeError('player snapshot session must match target session');return sendEncoded(session,encodeServerPlayerSnapshot(snapshot));},
    sendRemotePlayerSpawn(session,state){return sendEncoded(session,encodeRemotePlayerSpawn(state));},sendRemotePlayerSnapshot(session,state){return sendEncoded(session,encodeRemotePlayerSnapshot(state));},sendRemotePlayerDespawn(session,playerId){return sendEncoded(session,encodeRemotePlayerDespawn(playerId));},
    sendItemEntitySpawn(session,state){return sendEncoded(session,encodeItemEntitySpawn(state));},sendItemEntitySnapshot(session,state){return sendEncoded(session,encodeItemEntitySnapshot(state));},sendItemEntityDespawn(session,entityId,revision,reason){return sendEncoded(session,encodeItemEntityDespawn(entityId,revision,reason));},
    sendMiningProgress(session,state){session=assertClientSessionId(session);if(!state||state.session!==session)throw new RangeError('mining progress session must match target session');return sendEncoded(session,encodeMiningProgress(state));},
    async close(){for(const websocket of wss.clients)websocket.terminate();await new Promise(resolve=>wss.close(()=>resolve()));sessions.clear();if(httpServer.listening)await new Promise((resolve,reject)=>httpServer.close(error=>error?reject(error):resolve()));}
  };
}
