import {TERRAIN_GENERATOR_VERSION} from '../src/terrain-generator.js';
import {DEFAULT_SERVER_TICK_RATE} from '../src/server-world-info.js';
import {HOTBAR_START} from '../src/inventory-layout.js';
import {lookDirectionFromYawPitch} from '../src/player-orientation-rules.js';
import {PLAYER_EYE_HEIGHT} from '../src/player-environment-rules.js';
import {createMultiplayerServer} from './multiplayer-server.mjs';
import {ServerTerrainWorld} from './terrain-world.mjs';
import {AuthoritativeWorldSession} from './authoritative-world-session.mjs';
import {CreativeBlockBreakController} from './creative-block-break-controller.mjs';
import {SurvivalBlockBreakController} from './survival-block-break-controller.mjs';
import {CreativeBlockUseController,DEFAULT_INTERACTION_ACTIONS_PER_TICK} from './creative-block-use-controller.mjs';
import {ServerPlayerInventoryHub} from './player-inventory-state.mjs';
import {ServerItemEntityHub} from './item-entity-state.mjs';
import {RemotePlayerReplicationHub} from './remote-player-replication-hub.mjs';
import {normalizeRuntimeConfig} from './runtime-config.mjs';

function callback(value,label){if(typeof value!=='function')throw new TypeError(`${label} must be a function`);return value;}
function observer(value,label){const fn=callback(value,label);return event=>{try{fn(event);}catch{}};}

export function createAuthoritativeServerRuntime({config={},setIntervalFn=setInterval,clearIntervalFn=clearInterval,playerIdFactory=undefined,itemEntityIdFactory=undefined,onLog=()=>{},onError=()=>{}}={}){
  const normalized=normalizeRuntimeConfig(config),log=observer(onLog,'onLog'),report=observer(onError,'onError');
  const world=new ServerTerrainWorld({seed:normalized.seed,prompt:normalized.prompt,maxCacheChunks:normalized.terrainCacheChunks});
  let server=null,authoritative=null;
  const inventories=new ServerPlayerInventoryHub();
  const sendItemToAll=(kind,payload)=>{for(const session of [...(authoritative?.sessions||[])]){try{let wire=null;if(kind==='spawn')wire=server?.sendItemEntitySpawn(session,payload)??null;else if(kind==='snapshot')wire=server?.sendItemEntitySnapshot(session,payload)??null;else wire=server?.sendItemEntityDespawn(session,payload.entityId,payload.revision,payload.reason)??null;if(wire===null)report({source:'item-entity-replication',session,kind,payload,error:new Error('item entity transport unavailable')});}catch(error){report({source:'item-entity-replication',session,kind,payload,error});}}};
  const itemEntities=new ServerItemEntityHub({...(itemEntityIdFactory===undefined?{}:{entityIdFactory:callback(itemEntityIdFactory,'itemEntityIdFactory')}),onSpawn:state=>sendItemToAll('spawn',state),onSnapshot:state=>sendItemToAll('snapshot',state),onDespawn:message=>sendItemToAll('despawn',message),onError:event=>report({source:'item-entity',...event})});
  const replication=new RemotePlayerReplicationHub({sendSpawn:(session,state)=>server?.sendRemotePlayerSpawn(session,state)??null,sendSnapshot:(session,state)=>server?.sendRemotePlayerSnapshot(session,state)??null,sendDespawn:(session,playerId)=>server?.sendRemotePlayerDespawn(session,playerId)??null,...(playerIdFactory===undefined?{}:{playerIdFactory:callback(playerIdFactory,'playerIdFactory')}),onSendError:event=>report({source:'remote-replication',...event})});
  const commitBlockChange=(x,y,z,id)=>{const change=world.setBlock(x,y,z,id);if(!change.changed)return Object.freeze({...change,broadcast:0,failed:0});let broadcast=0,failed=0;for(const session of [...(authoritative?.sessions||[])]){try{const wire=server?.sendWorldBlockChange(session,{worldId:normalized.worldId,revision:change.revision,x:change.x,y:change.y,z:change.z,previous:change.previous,id:change.id})??null;if(wire===null){failed++;report({source:'world-change',session,change,error:new Error('world change transport unavailable')});}else broadcast++;}catch(error){failed++;report({source:'world-change',session,change,error});}}return Object.freeze({...change,broadcast,failed});};
  const replicateInventory=session=>{const snapshot=inventories.snapshot(session);try{const wire=server?.sendInventorySnapshot(session,snapshot)??null;if(wire===null){report({source:'inventory-replication',session,snapshot,error:new Error('inventory snapshot transport unavailable')});return Object.freeze({snapshot,replicated:false});}return Object.freeze({snapshot,replicated:true});}catch(error){report({source:'inventory-replication',session,snapshot,error});return Object.freeze({snapshot,replicated:false});}};
  const addPickupInventory=(session,id,count)=>{const before=inventories.snapshot(session).revision,remaining=inventories.addPickup(session,id,count),after=inventories.snapshot(session);if(after.revision!==before)replicateInventory(session);return remaining;};
  const processDropActions=(session,player,actions)=>{
    for(const action of actions){if(action.kind!=='drop'||player.mode==='spectator')continue;const stack=inventories.selectedStack(session,action.selectedSlot);if(!stack)continue;const direction=lookDirectionFromYawPitch(action.view.yaw,action.view.pitch),position={x:player.position.x+direction.x*.45,y:player.position.y+PLAYER_EYE_HEIGHT-.25+direction.y*.45,z:player.position.z+direction.z*.45},velocity={x:direction.x*4,y:direction.y*4+.2,z:direction.z*4};if(player.mode!=='creative'){const removed=inventories.remove(session,HOTBAR_START+action.selectedSlot,1);if(!removed)continue;replicateInventory(session);}try{itemEntities.spawn(stack.id,1,position,{velocity});}catch(error){if(player.mode!=='creative'){try{inventories.addPickup(session,stack.id,1);replicateInventory(session);}catch{}}report({source:'item-drop',session,action,error});}
    }
  };
  const creativeBreak=new CreativeBlockBreakController({world,setBlock:commitBlockChange});
  const survivalBreak=new SurvivalBlockBreakController({world,setBlock:commitBlockChange,onDrop:drop=>{try{itemEntities.spawn(drop.itemId,drop.count,drop.position,{velocity:{x:0,y:.35,z:0}});}catch(error){report({source:'survival-block-drop',session:drop.session,drop,error});}}});
  const creativeUse=new CreativeBlockUseController({world,setBlock:commitBlockChange,inventories});
  authoritative=new AuthoritativeWorldSession({world,getInputState:session=>server?.getSessionInputState(session)??null,sendPlayerSnapshot:(session,snapshot)=>{const wire=server?.sendPlayerSnapshot(session,snapshot)??null;if(wire!==null){try{creativeBreak.step(session,snapshot);}catch(error){report({source:'creative-block-break',session,error});}try{const input=server?.getSessionInputState(session),selected=input&&inventories.has(session)?inventories.selectedStack(session,input.selectedSlot):null;survivalBreak.step(session,snapshot,selected,{dt:1/DEFAULT_SERVER_TICK_RATE});}catch(error){report({source:'survival-block-break',session,error});}const actions=server?.drainSessionActions(session,DEFAULT_INTERACTION_ACTIONS_PER_TICK)??[];try{processDropActions(session,snapshot,actions);}catch(error){report({source:'item-drop',session,error});}try{creativeUse.step(session,snapshot,actions);}catch(error){report({source:'creative-block-use',session,error});}replication.update(session,snapshot);}return wire;},onTick:({dt})=>{const players=[];for(const session of authoritative.sessions){const snapshot=authoritative.snapshot(session);if(snapshot)players.push({session,mode:snapshot.mode,position:snapshot.position});}try{itemEntities.step(world,players,{dt,onPickup:(session,id,count)=>addPickupInventory(session,id,count)});}catch(error){report({source:'item-entity-tick',error});}},setIntervalFn,clearIntervalFn,onSessionError:event=>report({source:'world-session',...event}),defaultMode:normalized.mode,spawnX:normalized.spawnX,spawnZ:normalized.spawnZ,prefetchRadius:normalized.prefetchRadius});

  server=createMultiplayerServer({host:normalized.host,port:normalized.port,allowedOrigins:normalized.allowedOrigins,allowMissingOrigin:normalized.allowMissingOrigin,onSessionReady:({session})=>{
    const info=server.sendWorldInfo(session,{session,worldId:normalized.worldId,terrainVersion:TERRAIN_GENERATOR_VERSION,seed:normalized.seed,prompt:normalized.prompt,tickRate:DEFAULT_SERVER_TICK_RATE});if(info===null)throw new Error('world info transport is unavailable');
    const worldEdits=server.sendWorldEditSync(session,{worldId:normalized.worldId,revision:world.revision,edits:world.editEntries()});if(worldEdits===null)throw new Error('world edit sync transport is unavailable');
    const joined=authoritative.join(session,{mode:normalized.mode});try{inventories.join(session,{mode:joined.snapshot.mode});const inventory=server.sendInventorySnapshot(session,inventories.snapshot(session));if(inventory===null)throw new Error('inventory snapshot transport is unavailable');for(const state of itemEntities.states()){if(server.sendItemEntitySpawn(session,state)===null)throw new Error('item entity bootstrap transport is unavailable');}replication.join(session,joined.snapshot);}catch(error){if(inventories.has(session))inventories.leave(session);authoritative.leave(session);creativeBreak.remove(session);survivalBreak.remove(session);throw error;}
  },onInput:({session,message})=>{if(message?.kind==='control'){creativeBreak.observePrimary(session,message.payload.primary);survivalBreak.observePrimary(session,message.payload.primary);}},onSessionClose:({session})=>{if(session){creativeBreak.remove(session);survivalBreak.remove(session);if(inventories.has(session))inventories.leave(session);replication.leave(session);authoritative.leave(session);}},onSocketError:event=>report({source:'socket',...event})});

  let state='idle',address=null,stopPromise=null;
  const runtime={config:normalized,world,server,authoritative,inventories,itemEntities,replication,creativeBreak,survivalBreak,get state(){return state;},get running(){return state==='running';},get address(){return address;},
    setBlock:commitBlockChange,
    selectedStack(session){const input=server?.getSessionInputState(session);if(!input)throw new Error(`unknown input session: ${session}`);return inventories.selectedStack(session,input.selectedSlot);},
    spawnItemEntity(id,count,position,options={}){return itemEntities.spawn(id,count,position,options);},
    addInventoryItem(session,id,count=1){const before=inventories.snapshot(session).revision,remaining=inventories.add(session,id,count),after=inventories.snapshot(session);const replicationResult=after.revision===before?Object.freeze({snapshot:after,replicated:false}):replicateInventory(session);return Object.freeze({remaining,changed:after.revision!==before,snapshot:replicationResult.snapshot,replicated:replicationResult.replicated});},
    removeInventoryItem(session,slot,count=1){const before=inventories.snapshot(session).revision,removed=inventories.remove(session,slot,count),after=inventories.snapshot(session);const replicationResult=after.revision===before?Object.freeze({snapshot:after,replicated:false}):replicateInventory(session);return Object.freeze({removed,changed:after.revision!==before,snapshot:replicationResult.snapshot,replicated:replicationResult.replicated});},
    async start(){if(state==='running')return address;if(state!=='idle')throw new Error(`cannot start authoritative runtime while ${state}`);state='starting';try{address=await server.listen();authoritative.start();state='running';log({event:'listening',address,path:server.path,worldId:normalized.worldId,tickRate:DEFAULT_SERVER_TICK_RATE});return address;}catch(error){state='failed';creativeBreak.clear();survivalBreak.clear();inventories.close();itemEntities.close();replication.close();authoritative.close();try{await server.close();}catch{}report({source:'runtime-start',error});throw error;}},
    async stop(){if(state==='stopped')return;if(stopPromise)return stopPromise;stopPromise=(async()=>{const wasRunning=state==='running'||state==='starting'||state==='failed';state='stopping';creativeBreak.clear();survivalBreak.clear();inventories.close();itemEntities.close();replication.close();authoritative.close();if(wasRunning)try{await server.close();}catch(error){report({source:'runtime-stop',error});state='stopped';throw error;}state='stopped';log({event:'stopped',worldId:normalized.worldId});})();try{await stopPromise;}finally{stopPromise=null;}}
  };return runtime;
}
