from pathlib import Path

def rep(path,old,new,label):
    p=Path(path);t=p.read_text(encoding='utf-8');n=t.count(old)
    if n!=1: raise SystemExit(f'{label}: expected 1 match, got {n}')
    p.write_text(t.replace(old,new,1),encoding='utf-8')

rep('src/main.js',"import {bedPlacement,bedPartner,bedRespawnAnchor,isBedBlock} from './bed-rules.js';","import {bedPlacement,bedPartner,bedRespawnAnchor,isBedBlock} from './bed-rules.js';\nimport {resolveSleep} from './sleep-rules.js';",'sleep import')
rep('src/main.js',"function activateBed(hit){const anchor=bedRespawnAnchor(hit,hit?.id);if(!anchor||!setRespawnPoint(anchor))return false;ui.showToast('重生点已设置');return true;}","function activateBed(hit){\n  const anchor=bedRespawnAnchor(hit,hit?.id);if(!anchor||!setRespawnPoint(anchor))return false;\n  const sleep=resolveSleep({gameTime,weather,sleepingPlayers:1,totalPlayers:1,percentage:100});\n  if(!sleep.allowed){ui.showToast('重生点已设置 · 只能在夜晚或雷雨中睡觉');return true;}\n  if(!sleep.ready){ui.showToast(`重生点已设置 · 已有 ${sleep.sleepingPlayers}/${sleep.required} 名玩家睡觉`);return true;}\n  gameTime=sleep.nextTime;if(weather!=='clear'){weather='clear';weatherSystem?.setWeather(weather);}applySky();markSaveDirty();ui.showToast('已睡到清晨 · 重生点已设置');return true;\n}",'activateBed sleep')
rep('tests/e2e/smoke.spec.mjs',"  await page.waitForTimeout(250);await rightClickCanvas(page);await expect(page.locator('#toast')).toContainText('重生点已设置',{timeout:5_000});\n  await key(page,'Escape');await expect(page.locator('#pause-menu')).toHaveClass(/active/);","  await page.waitForTimeout(250);await rightClickCanvas(page);await expect(page.locator('#toast')).toContainText('重生点已设置',{timeout:5_000});\n  await runCommand(page,'/time set night');await expect.poll(async()=>{const text=await page.locator('#debug').innerText(),match=text.match(/Time\\s+(\\d+)/);return Number(match?.[1])>=12990;},{timeout:5_000,message:'night command should move the shared world clock into the sleep window'}).toBe(true);\n  await page.waitForTimeout(120);await rightClickCanvas(page);await expect(page.locator('#toast')).toContainText('已睡到清晨',{timeout:5_000});\n  await expect.poll(async()=>{const text=await page.locator('#debug').innerText(),match=text.match(/Time\\s+(\\d+)/),time=Number(match?.[1]);return Number.isFinite(time)&&time>=1000&&time<1200;},{timeout:5_000,message:'using the same bed at night should advance the shared world clock to morning'}).toBe(true);\n  await key(page,'Escape');await expect(page.locator('#pause-menu')).toHaveClass(/active/);",'bed e2e sleep')
