from pathlib import Path

def rep(path,old,new,label):
    p=Path(path);t=p.read_text(encoding='utf-8');n=t.count(old)
    if n!=1: raise SystemExit(f'{label}: expected 1 match, got {n}')
    p.write_text(t.replace(old,new,1),encoding='utf-8')

rep('README.md','两格床重生锚点、第一版护甲装备系统','两格床重生锚点与夜间睡眠跳夜、第一版护甲装备系统','readme summary')
rep('README.md','- 新增两格床重生锚点：床按玩家水平朝向原子放置 foot/head 两端，右键任一端都会通过同一 `respawnPoint` setter 设置持久化重生点；破坏任一端会联动移除配对端并只掉落 1 张床。当前不含睡觉、跳夜、占用、怪物限制、下界爆炸或半高床模型。','- 新增两格床重生锚点与基础睡眠：床按玩家水平朝向原子放置 foot/head 两端，使用任一端都会通过同一 `respawnPoint` setter 设置持久化重生点；夜晚/雨夜/雷暴中再次使用会通过共享 `sleep-rules` 把世界时间推进到清晨并清除降水。桌面右键与手机“使用”按钮走同一 `activateBed()`；当前不含睡眠动画、床占用、附近怪物限制、下界/末地床爆炸或半高床模型。','readme bed')

rep('docs/PROGRESS.md','Unified Control Intent + Absolute View Frame，共 12 套回归。','Unified Control Intent + Absolute View Frame + Bed Sleep/Quorum，共 13 套回归。','progress count')
rep('docs/PROGRESS.md','两格床重生锚点、第一版护甲、透明水 pass','两格床重生锚点与夜间睡眠跳夜、第一版护甲、透明水 pass','progress summary')
rep('docs/PROGRESS.md','- [x] Chromium 床 E2E：`/give bed`→真实背包槽 0→热栏 27→Pointer Lock/向下看→右键放置→右键床设重生点→v6 同时保存两端 edits/respawnPoint→异地死亡回床锚点\n- [ ] 装备掉落的普通死亡单独拾回断言、死亡统计、床睡眠/跳夜/占用/怪物限制/半高模型、`keepInventory`','- [x] Chromium 床 E2E：`/give bed`→真实背包槽 0→热栏 27→Pointer Lock/准星→右键放置→右键床设重生点→`/time set night`→再次使用同一床跳到约 1000 tick 清晨→v6 同时保存两端 edits/respawnPoint→异地死亡回床锚点\n- [x] `sleep-rules.js`：晴天/雨天睡眠窗口、雷暴例外、清晨目标和多人 sleeper percentage/quorum 纯规则；当前单人 runtime 使用 1/1 quorum，未来服务端直接传真实睡眠人数\n- [ ] 装备掉落的普通死亡单独拾回断言、死亡统计、床占用/怪物限制/半高模型、`keepInventory`','progress bed')

rep('docs/ARCHITECTURE.md','- `bed-rules.js` 把四个水平方向编码成 8 个 foot/head voxel ID，并纯逻辑负责朝向、配对端坐标和两端归一到同一床重生锚点；它不读取 World/Three.js。main 的 `placeBed()` 负责两端占位检查和原子写入，`breakBed()` 只在预期配对 ID 仍存在时联动删除，`activateBed()` 则只调用与 `/spawnpoint` 共用的 `setRespawnPoint()`。','- `bed-rules.js` 把四个水平方向编码成 8 个 foot/head voxel ID，并纯逻辑负责朝向、配对端坐标和两端归一到同一床重生锚点；它不读取 World/Three.js。main 的 `placeBed()` 负责两端占位检查和原子写入，`breakBed()` 只在预期配对 ID 仍存在时联动删除。\n- `sleep-rules.js` 独立负责晴天/雨天睡眠窗口、雷暴例外、清晨目标和 sleeper percentage/quorum；它不读取 DOM、设备类型或 World。`activateBed()` 先走共享 `setRespawnPoint()`，再调用 `resolveSleep()`；桌面/手机都从同一个 secondary/use 动作进入。当前单人传 1/1；未来 server-authoritative 联机由服务器提供 sleepingPlayers/totalPlayers/percentage，设备平台不得影响 quorum。','architecture sleep')

rep('docs/FILE_MANIFEST.md','| `src/bed-rules.js` | 四方向两格床 ID、朝向、foot/head partner 与统一床 respawn anchor | 纯逻辑；不读取 World/Three.js；runtime 只消费计划结果 |','| `src/bed-rules.js` | 四方向两格床 ID、朝向、foot/head partner 与统一床 respawn anchor | 纯逻辑；不读取 World/Three.js；runtime 只消费计划结果 |\n| `src/sleep-rules.js` | 晴天/雨天睡眠窗口、雷暴例外、清晨目标、多人 sleeper percentage/quorum | 纯逻辑；不读取设备/DOM；未来服务器与单机共享同一规则 |','manifest rules')
rep('docs/FILE_MANIFEST.md','| `scripts/check-bed.mjs` | 床朝向/配对/锚点、BLOCKS/ITEMS 元数据、3×3 配方和羊毛 loot 来源 | 纯逻辑/静态数据；不启动浏览器 |','| `scripts/check-bed.mjs` | 床朝向/配对/锚点、BLOCKS/ITEMS 元数据、3×3 配方和羊毛 loot 来源 | 纯逻辑/静态数据；不启动浏览器 |\n| `scripts/check-sleep.mjs` | 24000 tick 归一化、晴/雨睡眠窗口、雷暴例外、清晨目标、多人 quorum/percentage | 纯逻辑；第 13 套质量门 |','manifest check')
rep('docs/FILE_MANIFEST.md','`test:logic` 顺序跑基础/armor/water/oxygen/swim/weather/death/respawn/bed/mobile/controls/network-view 十二套测试','`test:logic` 顺序跑基础/armor/water/oxygen/swim/weather/death/respawn/bed/mobile/controls/network-view/sleep 十三套测试','manifest count')

rep('docs/TESTING.md','scripts/check-network-view.mjs\n```','scripts/check-network-view.mjs\nscripts/check-sleep.mjs\n```','testing list')
rep('docs/TESTING.md','`scripts/check-bed.mjs` 覆盖 8 个床 voxel ID 的唯一性、四方向 look→facing、foot/head 两端坐标、从任一端解析 partner、两端归一到同一 respawn anchor、BLOCKS/ITEMS/drop/tint 元数据、3×3 `3 wool + 3 planks -> bed` 配方消费，以及真实 sheep loot 的 `white_wool` 来源。2×2 工作区不得误匹配床配方。','`scripts/check-bed.mjs` 覆盖 8 个床 voxel ID 的唯一性、四方向 look→facing、foot/head 两端坐标、从任一端解析 partner、两端归一到同一 respawn anchor、BLOCKS/ITEMS/drop/tint 元数据、3×3 `3 wool + 3 planks -> bed` 配方消费，以及真实 sheep loot 的 `white_wool` 来源。2×2 工作区不得误匹配床配方。\n\n### Bed sleep / multiplayer-ready quorum\n\n`scripts/check-sleep.mjs` 覆盖 24000 tick 归一化、晴天 `12542..23459` 与雨天 `12010..23991` 睡眠窗口、雷暴任意时间可睡、清晨目标 1000、非负 32 位 sleeper percentage、超过 100% 的不可达 quorum、单人 ready 与多人 waiting→ready。设备类型不参与 sleeper 计算。','testing sleep section')
rep('docs/TESTING.md','3. 再次右键已放置床，必须出现“重生点已设置”。\n4. 暂停后只接受新鲜 v6 world record，并要求 edits 同时包含一对朝北床 ID `11/12`，且 `respawnPoint` 已保存。\n5. 返回游戏后传送到远处 `/kill`，显式“重生”后的公开 debug XYZ 必须回到保存的床锚点。\n6. 全程捕获 pageerror/console error；测试不直接修改 world edits、respawnPoint 或 IndexedDB。','3. 再次右键已放置床，必须出现“重生点已设置”。\n4. 通过正式 `/time set night` 把共享世界时钟推进到夜间，再次右键同一张床；必须出现“已睡到清晨”，公开 debug `Time` 必须回到约 1000 tick。\n5. 暂停后只接受新鲜 v6 world record，并要求 edits 包含合法 foot/head 配对且 `respawnPoint` 已保存。\n6. 返回游戏后传送到远处 `/kill`，显式“重生”后的公开 debug XYZ 必须回到保存的床锚点。\n7. 全程捕获 pageerror/console error；测试不直接修改 world edits、respawnPoint、gameTime 或 IndexedDB。','testing browser bed')

rep('CHANGELOG.md','- `static-checks` 同时检查 `src/*.js`、`scripts/*.mjs`；`npm run test:logic` 现在顺序执行基础、Equipment/Armor、Water Mesh、Oxygen/Drowning、Swimming/Buoyancy、Weather/Precipitation、Death Integration、Custom Respawn、Bed Rules、Mobile Device/Input、Unified Control Intent、Absolute View Frame 共十二套回归。','- `static-checks` 同时检查 `src/*.js`、`scripts/*.mjs`；`npm run test:logic` 现在顺序执行基础、Equipment/Armor、Water Mesh、Oxygen/Drowning、Swimming/Buoyancy、Weather/Precipitation、Death Integration、Custom Respawn、Bed Rules、Mobile Device/Input、Unified Control Intent、Absolute View Frame、Bed Sleep/Quorum 共十三套回归。','changelog count')
rep('CHANGELOG.md','- 新增 `scripts/check-bed.mjs`：覆盖 8 个床 ID、四方向朝向、foot/head 配对、统一重生锚点、方块/物品元数据、3×3 床配方和羊毛 loot 来源。','- 新增 `scripts/check-bed.mjs`：覆盖 8 个床 ID、四方向朝向、foot/head 配对、统一重生锚点、方块/物品元数据、3×3 床配方和羊毛 loot 来源。\n- 新增第 13 套 `scripts/check-sleep.mjs`：覆盖晴/雨睡眠窗口、雷暴例外、清晨目标和多人 sleeper percentage/quorum；浏览器床用例验证真实夜间用床会把共享 world clock 跳到清晨。','changelog check')
rep('CHANGELOG.md','- 新增第四条 Chromium 床用例：`/give bed` 后真实从背包主区移到热栏，再通过 Pointer Lock + 鼠标视角 + 右键放置/激活；v6 快照必须同时包含两端 bed edits 与 respawnPoint，异地死亡后显式重生回床锚点。','- 新增第四条 Chromium 床用例：`/give bed` 后真实从背包主区移到热栏，再通过 Pointer Lock + 鼠标视角 + 右键放置/激活；v6 快照必须同时包含两端 bed edits 与 respawnPoint，夜间再次使用同一床必须跳到约 1000 tick 清晨，异地死亡后显式重生仍回床锚点。\n- 新增 `sleep-rules.js`：当前单人 1/1 睡眠立即跳夜并清除降水，同时预先建模未来服务器的 sleepingPlayers/totalPlayers/percentage quorum；PC/手机不拥有各自的睡眠规则。','changelog runtime')
