from pathlib import Path


def patch(path, old, new, label):
    p=Path(path); text=p.read_text(encoding='utf-8'); count=text.count(old)
    if count!=1: raise SystemExit(f'{label}: expected 1 match, got {count}')
    p.write_text(text.replace(old,new,1),encoding='utf-8')

# Player exact-position respawn API.
patch('src/player.js',
"  respawn(x=0,z=0){this.hp=20;this.hunger=20;this.saturation=5;this.hurtUntil=-Infinity;this.spawn(x,z);}",
"  resetVitals(){this.hp=20;this.hunger=20;this.saturation=5;this.hurtUntil=-Infinity;}\n  respawn(x=0,z=0){this.resetVitals();this.spawn(x,z);}\n  respawnAt(position){\n    if(!position||![position.x,position.y,position.z].every(Number.isFinite))return false;const next=new THREE.Vector3(position.x,position.y,position.z);\n    if(this.mode!=='spectator'&&this.collides(next))return false;this.resetVitals();this.position.copy(next);this.velocity.set(0,0,0);this.swimCoverage=0;this.syncCamera();return true;\n  }",
'player respawnAt')

# Main runtime persistence/safety/resolution.
patch('src/main.js',"import {BLOCKS} from './blocks.js';","import {BLOCKS,WORLD_HEIGHT} from './blocks.js';\nimport {normalizeRespawnPoint,resolveRespawnPosition} from './respawn-rules.js';",'respawn imports')
patch('src/main.js',"let deathState=null;","let deathState=null,respawnPoint=null;",'respawn state')
patch('src/main.js',"function resetOxygen(){oxygenState=createOxygenState();headSubmerged=false;ui.renderOxygen(MAX_AIR_SECONDS,MAX_AIR_SECONDS,false);}","function resetOxygen(){oxygenState=createOxygenState();headSubmerged=false;ui.renderOxygen(MAX_AIR_SECONDS,MAX_AIR_SECONDS,false);}\nfunction isSafeRespawnPosition(value){\n  const point=normalizeRespawnPoint(value);if(!point||!world||!player||point.y<0||point.y>WORLD_HEIGHT+2)return false;const x=Math.floor(point.x),z=Math.floor(point.z),below=BLOCKS[world.getBlock(x,Math.floor(point.y-.05),z)],feet=BLOCKS[world.getBlock(x,Math.floor(point.y+.05),z)],eye=BLOCKS[world.getBlock(x,Math.floor(point.y+player.eye),z)];if(!below?.solid||feet?.solid||feet?.liquid||eye?.solid||eye?.liquid)return false;return !player.collides(new THREE.Vector3(point.x,point.y,point.z));\n}\nfunction preferredRespawn(){return respawnPoint?resolveRespawnPosition(respawnPoint,isSafeRespawnPosition):null;}\nfunction respawnAtPreferredPoint(){const custom=preferredRespawn();if(custom&&player?.respawnAt(custom))return{custom:true,position:custom};player?.respawn(0,0);return{custom:false,position:player?{x:player.position.x,y:player.position.y,z:player.position.z}:null};}", 'respawn resolver')
patch('src/main.js',"  weatherSystem=null;explosions=null;projectiles=null;hostileMobs=null;passiveMobs=null;experienceOrbs=null;drops=null;player=null;world=null;inventory=null;equipment=null;worldInfo=null;saveDirty=false;lastSavedPosition=null;lastAttackAt=-Infinity;totalXp=0;","  weatherSystem=null;explosions=null;projectiles=null;hostileMobs=null;passiveMobs=null;experienceOrbs=null;drops=null;player=null;world=null;inventory=null;equipment=null;worldInfo=null;respawnPoint=null;saveDirty=false;lastSavedPosition=null;lastAttackAt=-Infinity;totalXp=0;",'dispose respawn')
patch('src/main.js',"  const record={id:worldInfo.id,name:worldInfo.name,seed:worldInfo.seed,prompt:worldInfo.prompt,mode:player.mode,updatedAt:Date.now(),player:player.snapshot(),inventory:inventory.snapshot(),equipment:equipment.snapshot(),edits:world.exportEdits(),gameTime,weather,totalXp,version:5};","  const record={id:worldInfo.id,name:worldInfo.name,seed:worldInfo.seed,prompt:worldInfo.prompt,mode:player.mode,updatedAt:Date.now(),player:player.snapshot(),inventory:inventory.snapshot(),equipment:equipment.snapshot(),edits:world.exportEdits(),gameTime,weather,totalXp,respawnPoint:respawnPoint?{...respawnPoint}:null,version:6};",'save v6')
patch('src/main.js',"function completeRespawn(){\n  if(!player||!deathState)return;player.respawn(0,0);lastAttackAt=-Infinity;resetOxygen();deathState=null;deathScreen.hide();modeScreen(null);renderPlayerStatus();markSaveDirty();ui.showToast('已重生');pointer();\n}","function completeRespawn(){\n  if(!player||!deathState)return;const result=respawnAtPreferredPoint();lastAttackAt=-Infinity;resetOxygen();deathState=null;deathScreen.hide();modeScreen(null);renderPlayerStatus();markSaveDirty();ui.showToast(result.custom?'已在自定义重生点重生':'已在世界出生点重生');pointer();\n}", 'explicit preferred respawn')
patch('src/main.js',"  const mode=saved?.mode||selectedMode;worldInfo={id,seed:saved?.seed||seed,prompt:saved?.prompt||prompt,mode,name:saved?.name||name};gameTime=Number.isFinite(saved?.gameTime)?saved.gameTime:6000;weather=saved?.weather||'clear';totalXp=Number.isFinite(saved?.totalXp)?Math.max(0,Math.floor(saved.totalXp)):0;\n  const startPosition=saved?.player?.position,centerX=Number.isFinite(startPosition?.x)?startPosition.x:0,centerZ=Number.isFinite(startPosition?.z)?startPosition.z:0;modeScreen(null);ui.showLoading(true,saved?'读取世界存档':'启动地形 Worker',2);",
"  const mode=saved?.mode||selectedMode;worldInfo={id,seed:saved?.seed||seed,prompt:saved?.prompt||prompt,mode,name:saved?.name||name};gameTime=Number.isFinite(saved?.gameTime)?saved.gameTime:6000;weather=saved?.weather||'clear';totalXp=Number.isFinite(saved?.totalXp)?Math.max(0,Math.floor(saved.totalXp)):0;respawnPoint=normalizeRespawnPoint(saved?.respawnPoint);\n  const savedDead=Number.isFinite(saved?.player?.hp)&&saved.player.hp<=0,startPosition=savedDead&&respawnPoint?respawnPoint:saved?.player?.position,centerX=Number.isFinite(startPosition?.x)?startPosition.x:0,centerZ=Number.isFinite(startPosition?.z)?startPosition.z:0;modeScreen(null);ui.showLoading(true,saved?'读取世界存档':'启动地形 Worker',2);",'load respawn state')
patch('src/main.js',"  inventory=new Inventory(mode,saved?.inventory||null);equipment=new Equipment(saved?.equipment||null);player=new PlayerController(camera,canvas,world,scene);player.setMode(mode);const restored=saved?.player?player.restore(saved.player):false;if(!restored)player.spawn(centerX,centerZ);if(player.hp<=0)player.respawn(0,0);resetOxygen();",
"  inventory=new Inventory(mode,saved?.inventory||null);equipment=new Equipment(saved?.equipment||null);player=new PlayerController(camera,canvas,world,scene);player.setMode(mode);const restored=!savedDead&&saved?.player?player.restore(saved.player):false;if(!restored)player.spawn(centerX,centerZ);if(savedDead)respawnAtPreferredPoint();resetOxygen();",'dead save startup respawn')
patch('src/main.js',"setMode:mode=>{player.setMode(mode);worldInfo.mode=mode;if(!usesOxygen(mode))resetOxygen();markSaveDirty();},addXp:value=>addExperience(value),kill:()=>{if(deathState)return;player.hp=0;player.velocity.set(0,0,0);beginPlayerDeath('你被杀死了');},teleport:","setMode:mode=>{player.setMode(mode);worldInfo.mode=mode;if(!usesOxygen(mode))resetOxygen();markSaveDirty();},setSpawnpoint:(x,y,z)=>{const point=normalizeRespawnPoint({x,y,z});if(!point)return false;respawnPoint=point;markSaveDirty();return true;},addXp:value=>addExperience(value),kill:()=>{if(deathState)return;player.hp=0;player.velocity.set(0,0,0);beginPlayerDeath('你被杀死了');},teleport:",'spawnpoint context')

# Command regression.
patch('scripts/check.mjs',"  let mode='survival',time=0,weather='clear',killed=false,addedXp=0;const p={position:{x:1,y:2,z:3}},inventory=new Inventory('survival');\n  const ctx={player:p,inventory,inventoryChanged(){},setMode:v=>mode=v,addXp:v=>addedXp+=v,kill:()=>killed=true,teleport:(x,y,z)=>p.position={x,y,z},setTime:v=>time=v,setWeather:v=>weather=v};",
"  let mode='survival',time=0,weather='clear',killed=false,addedXp=0,spawnpoint=null;const p={position:{x:1,y:2,z:3}},inventory=new Inventory('survival');\n  const ctx={player:p,inventory,inventoryChanged(){},setMode:v=>mode=v,setSpawnpoint:(x,y,z)=>(spawnpoint={x,y,z},true),addXp:v=>addedXp+=v,kill:()=>killed=true,teleport:(x,y,z)=>p.position={x,y,z},setTime:v=>time=v,setWeather:v=>weather=v};",'command ctx')
patch('scripts/check.mjs',"  assert.equal(executeCommand('/tp ~1 70 ~-2',ctx).ok,true);assert.deepEqual(p.position,{x:2,y:70,z:1});\n  assert.equal(executeCommand('/xp add 16',ctx).ok,true);",
"  assert.equal(executeCommand('/tp ~1 70 ~-2',ctx).ok,true);assert.deepEqual(p.position,{x:2,y:70,z:1});\n  assert.equal(executeCommand('/spawnpoint',ctx).ok,true);assert.deepEqual(spawnpoint,{x:2,y:70,z:1});assert.equal(executeCommand('/spawnpoint ~1 ~2 ~-3',ctx).ok,true);assert.deepEqual(spawnpoint,{x:3,y:72,z:-2});assert.equal(executeCommand('/spawnpoint 1 2',ctx).ok,false);\n  assert.equal(executeCommand('/xp add 16',ctx).ok,true);",'command spawnpoint checks')

# Browser helpers/version + dedicated custom respawn world.
patch('tests/e2e/smoke.spec.mjs',"async function debugY(page){\n  const text=await page.locator('#debug').innerText(),match=text.match(/XYZ\\s+[-\\d.]+\\s*\\/\\s*([-\\d.]+)\\s*\\//);\n  if(!match)throw new Error(`cannot parse player Y from debug HUD: ${text}`);\n  return Number(match[1]);\n}","async function debugXYZ(page){\n  const text=await page.locator('#debug').innerText(),match=text.match(/XYZ\\s+([-\\d.]+)\\s*\\/\\s*([-\\d.]+)\\s*\\/\\s*([-\\d.]+)/);\n  if(!match)throw new Error(`cannot parse player XYZ from debug HUD: ${text}`);return{x:Number(match[1]),y:Number(match[2]),z:Number(match[3])};\n}\nasync function debugY(page){return (await debugXYZ(page)).y;}", 'debug XYZ helper')
patch('tests/e2e/smoke.spec.mjs',"return{version:record.version,chest:record.equipment?.slots?.chest?.id||null,weather:record.weather,hasTransientAir:Object.hasOwn(record,'oxygen')};\n  },{timeout:10_000,message:'a fresh pause save should persist armor and clear weather but not transient oxygen state'}).toEqual({version:5,chest:'leather_chestplate',weather:'clear',hasTransientAir:false});","return{version:record.version,chest:record.equipment?.slots?.chest?.id||null,weather:record.weather,hasTransientAir:Object.hasOwn(record,'oxygen')};\n  },{timeout:10_000,message:'a fresh pause save should persist armor and clear weather but not transient oxygen state'}).toEqual({version:6,chest:'leather_chestplate',weather:'clear',hasTransientAir:false});",'browser save version')

p=Path('tests/e2e/smoke.spec.mjs'); text=p.read_text(encoding='utf-8')
append="""

test('custom spawnpoint persists and explicit respawn returns to it',async({page})=>{
  const pageErrors=[],consoleErrors=[];page.on('pageerror',error=>pageErrors.push(error.message));page.on('console',message=>{if(message.type()==='error')consoleErrors.push(message.text());});
  await page.goto('/');await page.getByRole('button',{name:'单人游戏'}).click();await page.locator('#world-name').fill('CI Custom Respawn');await page.locator('#world-seed').fill('ci-custom-respawn-2026');await page.locator('#game-mode').selectOption('survival');await page.locator('#terrain-prompt').fill('平原');await page.getByRole('button',{name:'创建 / 进入'}).click();
  await expect(page.locator('#loading')).toHaveClass(/hidden/,{timeout:60_000});await expect(page.locator('#hud')).not.toHaveClass(/hidden/);
  await runCommand(page,'/tp 7 35 7');
  await expect.poll(async()=>{const a=await debugXYZ(page);await page.waitForTimeout(250);const b=await debugXYZ(page);return Math.abs(a.y-b.y)<.03&&b.y>0;},{timeout:10_000,message:'player should settle on terrain before setting spawnpoint'}).toBe(true);
  const custom=await debugXYZ(page);await runCommand(page,'/spawnpoint');const saveStarted=await page.evaluate(()=>Date.now());await key(page,'Escape');await expect(page.locator('#pause-menu')).toHaveClass(/active/);
  await expect.poll(async()=>{const record=(await savedWorlds(page)).find(world=>world.name==='CI Custom Respawn');if(!record||Number(record.updatedAt)<saveStarted||!record.respawnPoint)return null;return{version:record.version,x:Number(record.respawnPoint.x.toFixed(1)),y:Number(record.respawnPoint.y.toFixed(1)),z:Number(record.respawnPoint.z.toFixed(1))};},{timeout:10_000,message:'spawnpoint should persist in a fresh v6 world snapshot'}).toEqual({version:6,x:custom.x,y:custom.y,z:custom.z});
  await page.getByRole('button',{name:'返回游戏'}).click();await runCommand(page,'/tp -7 35 -7');await runCommand(page,'/kill');await expect(page.locator('#death-menu')).toHaveClass(/active/,{timeout:10_000});await page.getByRole('button',{name:'重生'}).click();await expect(page.locator('#death-menu')).not.toHaveClass(/active/);
  await expect.poll(async()=>{const p=await debugXYZ(page);return Math.abs(p.x-custom.x)<.15&&Math.abs(p.y-custom.y)<.15&&Math.abs(p.z-custom.z)<.15;},{timeout:5_000,message:'explicit respawn should return to the persisted custom spawnpoint'}).toBe(true);
  expect(pageErrors).toEqual([]);expect(consoleErrors).toEqual([]);
});
"""
if "custom spawnpoint persists and explicit respawn returns to it" in text: raise SystemExit('e2e custom respawn already present')
p.write_text(text.rstrip()+append,encoding='utf-8')
print('custom respawn runtime patch: PASS')
