import {UI} from './ui.js';
import {FURNACE_SLOT} from './smelting.js';
import {currentMultiplayerFurnaceSnapshot,hasMultiplayerFurnaceSender,sendMultiplayerFurnaceTransaction,subscribeMultiplayerFurnaceSnapshots,subscribeMultiplayerFurnaceResults,subscribeMultiplayerFurnaceCloses} from './multiplayer-furnace-channel.js';

let activeUi=null,panel=null,mainGrid=null,hotbarGrid=null,inputSlot=null,fuelSlot=null,outputSlot=null,burnFill=null,cookClip=null,status=null;
function ensureStyles(){if(typeof document==='undefined'||document.querySelector('link[data-furnace-ui]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href='./furnace.css';link.dataset.furnaceUi='true';document.head.append(link);}
function ensurePanel(){if(typeof document==='undefined')return null;if(panel?.isConnected)return panel;ensureStyles();panel=document.createElement('section');panel.id='furnace';panel.className='inventory hidden';panel.setAttribute('aria-label','熔炉');panel.innerHTML='<div class="inventory-panel furnace-panel"><button class="mobile-panel-close furnace-close" type="button" aria-label="关闭熔炉">×</button><div class="furnace-title">熔炉</div><div class="furnace-inventory-title">物品栏</div><div class="furnace-burn-clip"><div class="furnace-burn-fill"></div></div><div class="furnace-cook-clip"><div class="furnace-cook-fill"></div></div><div class="furnace-input-host"></div><div class="furnace-fuel-host"></div><div class="furnace-output-host"></div><div class="furnace-main-grid"></div><div class="furnace-hotbar-grid"></div><div class="furnace-status" role="status" aria-live="polite"></div></div>';const app=document.querySelector('#app')||document.body;app.append(panel);mainGrid=panel.querySelector('.furnace-main-grid');hotbarGrid=panel.querySelector('.furnace-hotbar-grid');burnFill=panel.querySelector('.furnace-burn-fill');cookClip=panel.querySelector('.furnace-cook-clip');status=panel.querySelector('.furnace-status');panel.querySelector('.furnace-close').addEventListener('click',()=>requestClose());panel.addEventListener('pointerdown',event=>{const target=event.target.closest('[data-furnace-slot],[data-furnace-output]');if(!target||(event.button!==0&&event.button!==2))return;event.preventDefault();event.stopPropagation();try{if(target.dataset.furnaceOutput!==undefined)sendMultiplayerFurnaceTransaction({type:'take-output',button:event.button,shift:!!event.shiftKey});else sendMultiplayerFurnaceTransaction({type:'slot-click',slot:Number(target.dataset.furnaceSlot),button:event.button,shift:!!event.shiftKey});}catch(error){activeUi?.showToast?.(`熔炉操作发送失败：${error?.message||error}`);}});return panel;}
function requestClose(){const snapshot=currentMultiplayerFurnaceSnapshot();if(snapshot&&hasMultiplayerFurnaceSender())try{sendMultiplayerFurnaceTransaction({type:'close'});}catch(error){activeUi?.showToast?.(`熔炉收尾操作发送失败：${error?.message||error}`);}if(panel)panel.classList.add('hidden');activeUi?.renderCursor?.();}
function buildInventory(ui){ensurePanel();if(!mainGrid||!hotbarGrid)return;mainGrid.textContent='';hotbarGrid.textContent='';for(let i=0;i<27;i++)mainGrid.append(ui.makeSlot(ui.inventoryModel?.slots[i]||null,{index:i}));for(let i=27;i<36;i++)hotbarGrid.append(ui.makeSlot(ui.inventoryModel?.slots[i]||null,{index:i}));}
function renderFurnaceSlot(ui,hostSelector,stack,{slot=null,output=false,className=''}){const host=panel.querySelector(hostSelector);host.textContent='';const button=ui.makeSlot(stack||null);button.classList.add('furnace-slot',className);if(output)button.dataset.furnaceOutput='';else button.dataset.furnaceSlot=String(slot);host.append(button);return button;}
function renderSnapshot(snapshot){ensurePanel();if(!snapshot){panel.classList.add('hidden');activeUi?.renderCursor?.();return;}if(!activeUi)return;activeUi.inventory?.classList.add('hidden');activeUi.workbench?.classList.add('hidden');panel.classList.remove('hidden');buildInventory(activeUi);inputSlot=renderFurnaceSlot(activeUi,'.furnace-input-host',snapshot.slots[FURNACE_SLOT.INPUT],{slot:FURNACE_SLOT.INPUT,className:'furnace-input'});fuelSlot=renderFurnaceSlot(activeUi,'.furnace-fuel-host',snapshot.slots[FURNACE_SLOT.FUEL],{slot:FURNACE_SLOT.FUEL,className:'furnace-fuel'});outputSlot=renderFurnaceSlot(activeUi,'.furnace-output-host',snapshot.slots[FURNACE_SLOT.OUTPUT],{output:true,className:'furnace-output'});const burn=snapshot.burnTotal>0?Math.max(0,Math.min(1,snapshot.burnRemaining/snapshot.burnTotal)):0,cook=snapshot.cookTotal>0?Math.max(0,Math.min(1,snapshot.cookProgress/snapshot.cookTotal)):0;burnFill.style.transform=`translateY(${Math.round(28*(1-burn))}px)`;cookClip.style.width=`${Math.round(48*cook)}px`;status.textContent=snapshot.lit?`燃烧中 · ${Math.round(cook*100)}%`:(snapshot.slots[FURNACE_SLOT.INPUT]?'等待燃料':'');activeUi.renderCursor?.();}

const originalBindInventory=UI.prototype.bindInventory;
UI.prototype.bindInventory=function(...args){activeUi=this;const result=originalBindInventory.apply(this,args);buildInventory(this);const snapshot=currentMultiplayerFurnaceSnapshot();if(snapshot)renderSnapshot(snapshot);return result;};
const originalRenderInventoryPanels=UI.prototype.renderInventoryPanels;
UI.prototype.renderInventoryPanels=function(...args){const result=originalRenderInventoryPanels.apply(this,args);if(activeUi===this)buildInventory(this);return result;};
const originalHasOpenPanel=UI.prototype.hasOpenPanel;
UI.prototype.hasOpenPanel=function(){return originalHasOpenPanel.call(this)||!!(ensurePanel()&&!panel.classList.contains('hidden'));};
const originalOpenInventory=UI.prototype.openInventory;
UI.prototype.openInventory=function(...args){if(panel&&!panel.classList.contains('hidden'))requestClose();return originalOpenInventory.apply(this,args);};
const originalOpenWorkbench=UI.prototype.openWorkbench;
UI.prototype.openWorkbench=function(...args){if(panel&&!panel.classList.contains('hidden'))requestClose();return originalOpenWorkbench.apply(this,args);};
const originalClosePanels=UI.prototype.closePanels;
UI.prototype.closePanels=function(...args){if(panel&&!panel.classList.contains('hidden')){requestClose();return[];}return originalClosePanels.apply(this,args);};

ensurePanel();
subscribeMultiplayerFurnaceSnapshots(snapshot=>renderSnapshot(snapshot));
subscribeMultiplayerFurnaceResults(result=>{if(result.ok)return;if(result.code==='stale-revision')activeUi?.showToast?.('熔炉或背包状态已由服务器更新，请重试');else if(result.code==='out-of-range')activeUi?.showToast?.('距离熔炉过远，容器已关闭');else if(result.code==='block-removed')activeUi?.showToast?.('熔炉已被移除，容器已关闭');else activeUi?.showToast?.(`熔炉操作被服务器拒绝：${result.code}`);});
subscribeMultiplayerFurnaceCloses(message=>{panel?.classList.add('hidden');activeUi?.renderCursor?.();if(message.reason==='out-of-range')activeUi?.showToast?.('距离熔炉过远，容器已关闭');else if(message.reason==='block-removed')activeUi?.showToast?.('熔炉已被移除，容器已关闭');else if(message.reason==='mode-invalid')activeUi?.showToast?.('当前游戏模式无法继续使用熔炉');else if(message.reason==='player-dead')activeUi?.showToast?.('死亡后熔炉界面已关闭');});
