import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.169.0/build/three.module.js';
import {BLOCKS} from './blocks.js';

export class PlayerController{
  constructor(camera,canvas,world){this.camera=camera;this.canvas=canvas;this.world=world;this.position=new THREE.Vector3(0,40,0);this.velocity=new THREE.Vector3();this.yaw=0;this.pitch=0;this.keys=new Set();this.grounded=false;this.flying=false;this.mode='survival';this.hp=20;this.hunger=20;this.saturation=5;this.eye=1.62;this.height=1.8;this.radius=.3;this.walk=4.3;this.sprint=5.6;this.bind()}
  bind(){this.onKeyDown=e=>{this.keys.add(e.code);if(e.code==='Space')e.preventDefault()};this.onKeyUp=e=>this.keys.delete(e.code);this.onMove=e=>{if(document.pointerLockElement!==this.canvas)return;this.yaw-=e.movementX*.0022;this.pitch-=e.movementY*.0022;this.pitch=Math.max(-1.553,Math.min(1.553,this.pitch))};window.addEventListener('keydown',this.onKeyDown);window.addEventListener('keyup',this.onKeyUp);document.addEventListener('mousemove',this.onMove)}
  setMode(m){this.mode=m;this.flying=m==='creative'}
  spawn(x,z){const y=this.world.highestSolid(x,z)+1.001;this.position.set(x+.5,y,z+.5);this.velocity.set(0,0,0);this.syncCamera()}
  collides(pos){const r=this.radius,h=this.height,eps=.001;const minX=Math.floor(pos.x-r+eps),maxX=Math.floor(pos.x+r-eps),minY=Math.floor(pos.y+eps),maxY=Math.floor(pos.y+h-eps),minZ=Math.floor(pos.z-r+eps),maxZ=Math.floor(pos.z+r-eps);for(let x=minX;x<=maxX;x++)for(let y=minY;y<=maxY;y++)for(let z=minZ;z<=maxZ;z++){const b=BLOCKS[this.world.getBlock(x,y,z)];if(b?.solid)return true}return false}
  moveAxis(axis,amount){if(!amount)return;const next=this.position.clone();next[axis]+=amount;if(!this.collides(next)){this.position.copy(next);return true}if(axis==='y'&&amount<0)this.grounded=true;this.velocity[axis]=0;return false}
  update(dt){dt=Math.min(dt,.05);const forward=(this.keys.has('KeyW')?1:0)-(this.keys.has('KeyS')?1:0),side=(this.keys.has('KeyD')?1:0)-(this.keys.has('KeyA')?1:0);const sprint=this.keys.has('ControlLeft')||this.keys.has('ControlRight');const sneak=this.keys.has('ShiftLeft')||this.keys.has('ShiftRight');const speed=(sprint?this.sprint:this.walk)*(sneak?.35:1);const dir=new THREE.Vector3();if(forward||side){dir.set(Math.sin(this.yaw)*forward+Math.cos(this.yaw)*side,0,-Math.cos(this.yaw)*forward+Math.sin(this.yaw)*side).normalize().multiplyScalar(speed*dt)}
    if(this.flying){const vertical=((this.keys.has('Space')?1:0)-(sneak?1:0))*7*dt;this.moveAxis('x',dir.x);this.moveAxis('z',dir.z);this.moveAxis('y',vertical);this.velocity.set(0,0,0)}else{this.grounded=false;this.velocity.y-=24*dt;if(this.keys.has('Space')&&this.isGroundedProbe())this.velocity.y=8.2;this.moveAxis('x',dir.x);this.moveAxis('z',dir.z);this.moveAxis('y',this.velocity.y*dt);if(this.position.y<-10){this.hp=Math.max(0,this.hp-5);this.spawn(0,0)}}this.syncCamera()}
  isGroundedProbe(){const p=this.position.clone();p.y-=.06;return this.collides(p)}
  syncCamera(){this.camera.position.set(this.position.x,this.position.y+this.eye,this.position.z);this.camera.rotation.order='YXZ';this.camera.rotation.y=this.yaw;this.camera.rotation.x=this.pitch}
  dispose(){window.removeEventListener('keydown',this.onKeyDown);window.removeEventListener('keyup',this.onKeyUp);document.removeEventListener('mousemove',this.onMove)}
}
