import {BLOCKS,HOTBAR_DEFAULT,ATLAS_COLS,ATLAS_ROWS} from './blocks.js';
export class UI{
  constructor(){this.main=document.querySelector('#main-menu');this.worldMenu=document.querySelector('#world-menu');this.pause=document.querySelector('#pause-menu');this.hud=document.querySelector('#hud');this.inventory=document.querySelector('#inventory');this.loading=document.querySelector('#loading');this.hotbar=document.querySelector('#hotbar');this.invGrid=document.querySelector('#inventory-grid');this.invHotbar=document.querySelector('#inventory-hotbar');this.hearts=document.querySelector('#hearts');this.hunger=document.querySelector('#hunger');this.xp=document.querySelector('#xp-bar');this.level=document.querySelector('#xp-level');this.debug=document.querySelector('#debug');this.toast=document.querySelector('#toast');this.breakMeter=document.querySelector('#break-meter');this.loadingBar=document.querySelector('#loading-bar');this.loadingDetail=document.querySelector('#loading-detail');this.selected=0;this.items=structuredClone(HOTBAR_DEFAULT);this.build()}
  showScreen(el){for(const s of document.querySelectorAll('.screen'))s.classList.remove('active');if(el)el.classList.add('active')}
  build(){this.renderStatus(20,20,0,0);this.renderHotbar();for(let i=0;i<27;i++)this.invGrid.append(this.makeSlot(null));for(const it of this.items)this.invHotbar.append(this.makeSlot(it))}
  swatch(tile){const d=document.createElement('div');d.className='slot-swatch';const tx=tile%ATLAS_COLS,ty=Math.floor(tile/ATLAS_COLS);d.style.backgroundPosition=`-${tx*32}px -${ty*32}px`;return d}
  makeSlot(item,key){const s=document.createElement('div');s.className='inv-slot';if(item){s.append(this.swatch(BLOCKS[item.block].tiles[0]));const c=document.createElement('span');c.className='slot-count';c.textContent=item.count;s.append(c)}if(key){const k=document.createElement('span');k.className='slot-key';k.textContent=key;s.append(k)}return s}
  renderHotbar(){this.hotbar.textContent='';this.items.forEach((it,i)=>{const s=this.makeSlot(it,String(i+1));s.classList.add('hotbar-slot');if(i===this.selected)s.classList.add('selected');this.hotbar.append(s)})}
  select(i){this.selected=(i+9)%9;this.renderHotbar();const it=this.items[this.selected];if(it)this.showToast(BLOCKS[it.block].name)}
  selectedBlock(){return this.items[this.selected]?.block||0}
  renderStatus(hp,hunger,xp,level){this.hearts.textContent='';this.hunger.textContent='';for(let i=0;i<10;i++){const h=document.createElement('i');h.className='heart'+(hp>=i*2+1?'':' empty');this.hearts.append(h);const f=document.createElement('i');f.className='food'+(hunger>=i*2+1?'':' empty');this.hunger.append(f)}this.xp.style.width=`${Math.max(0,Math.min(100,xp))}%`;this.level.textContent=level}
  showLoading(show,detail='准备区块',p=0){this.loading.classList.toggle('hidden',!show);this.loadingDetail.textContent=detail;this.loadingBar.style.width=`${p}%`}
  showToast(text){this.toast.textContent=text;this.toast.classList.remove('hidden');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>this.toast.classList.add('hidden'),900)}
  setBreak(p){this.breakMeter.classList.toggle('hidden',p<=0||p>=1);this.breakMeter.querySelector('span').style.width=`${p*100}%`}
}
