import {encodeClientInputEnvelope} from './client-input-envelope.js';
import {nextNetworkSequence,NetworkSequenceGate} from './network-sequence.js';
import {MULTIPLAYER_SUBPROTOCOL,decodeServerHandshake,encodeClientHello} from './multiplayer-handshake.js';
import {MULTIPLAYER_COMMAND_RESULT_KIND,decodeMultiplayerCommandResult,encodeMultiplayerCommandRequest} from './multiplayer-command-wire.js';
import {MULTIPLAYER_CHAT_MESSAGE_KIND,decodeMultiplayerChatMessage,encodeMultiplayerChatSend} from './multiplayer-chat-wire.js';
import {INVENTORY_TRANSACTION_RESULT_KIND,decodeInventoryTransactionResult,encodeInventoryTransactionRequest} from './inventory-transaction-wire.js';
import {EQUIPMENT_TRANSACTION_RESULT_KIND,decodeEquipmentTransactionResult,encodeEquipmentTransactionRequest} from './equipment-transaction-wire.js';
import {PLAYER_CRAFTING_TRANSACTION_RESULT_KIND,decodePlayerCraftingTransactionResult,encodePlayerCraftingTransactionRequest} from './player-crafting-transaction-wire.js';
import {SERVER_INVENTORY_SNAPSHOT_KIND,decodeServerInventorySnapshot} from './server-inventory-snapshot.js';
import {SERVER_EQUIPMENT_SNAPSHOT_KIND,decodeServerEquipmentSnapshot} from './server-equipment-snapshot.js';
import {SERVER_PLAYER_CRAFTING_SNAPSHOT_KIND,decodeServerPlayerCraftingSnapshot} from './server-player-crafting-snapshot.js';
import {decodeServerPlayerSnapshot} from './server-player-snapshot.js';
import {SERVER_WORLD_INFO_KIND,decodeServerWorldInfo} from './server-world-info.js';
import {REMOTE_PLAYER_SPAWN_KIND,REMOTE_PLAYER_SNAPSHOT_KIND,REMOTE_PLAYER_DESPAWN_KIND,decodeRemotePlayerReplication} from './remote-player-replication.js';
import {ITEM_ENTITY_SPAWN_KIND,ITEM_ENTITY_SNAPSHOT_KIND,ITEM_ENTITY_DESPAWN_KIND,decodeItemEntityReplication} from './item-entity-replication.js';
import {MINING_PROGRESS_KIND,decodeMiningProgress} from './mining-progress-replication.js';
import {WORLD_EDIT_SYNC_BEGIN_KIND,WORLD_EDIT_SYNC_CHUNK_KIND,WORLD_EDIT_SYNC_END_KIND,WorldEditSyncAssembler} from './world-edit-replication.js';

export const WEBSOCKET_CLIENT_STATES=Object.freeze(['idle','connecting','handshaking','ready','rejected','closed','error']);
export const DEFAULT_HANDSHAKE_TIMEOUT_MS=5000;
export const HANDSHAKE_TIMEOUT_CLOSE_CODE=4000;
export const MAX_PENDING_MULTIPLAYER_COMMANDS=16;
export const MAX_PENDING_INVENTORY_TRANSACTIONS=1;
export const MAX_PENDING_EQUIPMENT_TRANSACTIONS=1;
export const MAX_PENDING_PLAYER_CRAFTING_TRANSACTIONS=1;

function assertSocketFactory(factory){if(typeof factory!=='function')throw new TypeError('socketFactory must be a function');return factory;}
function assertCallback(value,label){if(typeof value!=='function')throw new TypeError(`${label} must be a function`);return value;}
function assertTimeout(value){if(!Number.isInteger(value)||value<250||value>60000)throw new RangeError('handshake timeout must be an integer from 250 to 60000 ms');return value;}

export function createBrowserWebSocket(url,protocol){const WebSocketCtor=globalThis.WebSocket;if(typeof WebSocketCtor!=='function')throw new Error('WebSocket API is not available in this runtime');return new WebSocketCtor(url,protocol);}
export function normalizeWebSocketUrl(value,{allowInsecure=false}={}){if(typeof value!=='string'||!value.trim())throw new TypeError('websocket url must be a non-empty string');let url;try{url=new URL(value);}catch{throw new RangeError('websocket url must be an absolute URL');}if(url.username||url.password)throw new RangeError('websocket url must not contain embedded credentials');if(url.hash)throw new RangeError('websocket url must not contain a fragment');if(url.protocol==='wss:')return url.href;if(url.protocol==='ws:'&&allowInsecure)return url.href;if(url.protocol==='ws:')throw new RangeError('insecure ws:// requires explicit allowInsecure=true');throw new RangeError('websocket url must use ws:// or wss://');}
function parseJsonServerMessage(data){if(typeof data!=='string')throw new TypeError('server websocket messages must be UTF-8 JSON text');let parsed;try{parsed=JSON.parse(data);}catch{throw new RangeError('server websocket message must contain valid JSON');}if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new TypeError('server websocket message must contain a JSON object');return parsed;}
function isInitialWorldEditKind(kind){return kind===WORLD_EDIT_SYNC_BEGIN_KIND||kind===WORLD_EDIT_SYNC_CHUNK_KIND||kind===WORLD_EDIT_SYNC_END_KIND;}

export class MultiplayerWebSocketClient{
  constructor({socketFactory=createBrowserWebSocket,onStateChange=()=>{},onProtocolError=()=>{},onWorldInfo=()=>{},onWorldEditSync=()=>{},onInventorySnapshot=()=>{},onInventoryTransactionResult=()=>{},onEquipmentSnapshot=()=>{},onEquipmentTransactionResult=()=>{},onPlayerCraftingSnapshot=()=>{},onPlayerCraftingTransactionResult=()=>{},onPlayerSnapshot=()=>{},onRemotePlayerSpawn=()=>{},onRemotePlayerSnapshot=()=>{},onRemotePlayerDespawn=()=>{},onItemEntitySpawn=()=>{},onItemEntitySnapshot=()=>{},onItemEntityDespawn=()=>{},onMiningProgress=()=>{},onCommandResult=()=>{},onChatMessage=()=>{},handshakeTimeoutMs=DEFAULT_HANDSHAKE_TIMEOUT_MS,setTimer=setTimeout,clearTimer=clearTimeout,allowInsecure=false}={}){
    this.socketFactory=assertSocketFactory(socketFactory);this.onStateChange=assertCallback(onStateChange,'onStateChange');this.onProtocolError=assertCallback(onProtocolError,'onProtocolError');this.onWorldInfo=assertCallback(onWorldInfo,'onWorldInfo');this.onWorldEditSync=assertCallback(onWorldEditSync,'onWorldEditSync');this.onInventorySnapshot=assertCallback(onInventorySnapshot,'onInventorySnapshot');this.onInventoryTransactionResult=assertCallback(onInventoryTransactionResult,'onInventoryTransactionResult');this.onEquipmentSnapshot=assertCallback(onEquipmentSnapshot,'onEquipmentSnapshot');this.onEquipmentTransactionResult=assertCallback(onEquipmentTransactionResult,'onEquipmentTransactionResult');this.onPlayerCraftingSnapshot=assertCallback(onPlayerCraftingSnapshot,'onPlayerCraftingSnapshot');this.onPlayerCraftingTransactionResult=assertCallback(onPlayerCraftingTransactionResult,'onPlayerCraftingTransactionResult');this.onPlayerSnapshot=assertCallback(onPlayerSnapshot,'onPlayerSnapshot');this.onRemotePlayerSpawn=assertCallback(onRemotePlayerSpawn,'onRemotePlayerSpawn');this.onRemotePlayerSnapshot=assertCallback(onRemotePlayerSnapshot,'onRemotePlayerSnapshot');this.onRemotePlayerDespawn=assertCallback(onRemotePlayerDespawn,'onRemotePlayerDespawn');this.onItemEntitySpawn=assertCallback(onItemEntitySpawn,'onItemEntitySpawn');this.onItemEntitySnapshot=assertCallback(onItemEntitySnapshot,'onItemEntitySnapshot');this.onItemEntityDespawn=assertCallback(onItemEntityDespawn,'onItemEntityDespawn');this.onMiningProgress=assertCallback(onMiningProgress,'onMiningProgress');this.onCommandResult=assertCallback(onCommandResult,'onCommandResult');this.onChatMessage=assertCallback(onChatMessage,'onChatMessage');
    this.handshakeTimeoutMs=assertTimeout(handshakeTimeoutMs);this.setTimer=assertCallback(setTimer,'setTimer');this.clearTimer=assertCallback(clearTimer,'clearTimer');this.allowInsecure=!!allowInsecure;this.socket=null;this.state='idle';this.session=null;this.worldInfo=null;this.inventorySnapshot=null;this.equipmentSnapshot=null;this.playerCraftingSnapshot=null;this.worldEditSync=null;this.worldEditAssembler=null;this.packetSeq=0;this.commandRequestSeq=0;this.chatSendSeq=0;this.inventoryTransactionRequestSeq=0;this.equipmentTransactionRequestSeq=0;this.playerCraftingTransactionRequestSeq=0;this.pendingCommands=new Set();this.pendingInventoryTransactions=new Set();this.pendingEquipmentTransactions=new Set();this.pendingPlayerCraftingTransactions=new Set();this.handshakeTimer=null;this.snapshotGate=new NetworkSequenceGate();this.inventoryGate=new NetworkSequenceGate();this.equipmentGate=new NetworkSequenceGate();this.playerCraftingGate=new NetworkSequenceGate();this.miningProgressGate=new NetworkSequenceGate();this.chatMessageGate=new NetworkSequenceGate();this.remotePlayerGates=new Map();this.itemEntityGates=new Map();
  }

  setState(next,detail=null){if(this.state===next)return;this.state=next;this.onStateChange({state:next,detail});}
  clearHandshakeTimer(){if(this.handshakeTimer!==null){this.clearTimer(this.handshakeTimer);this.handshakeTimer=null;}}
  resetRealtimeState(){this.snapshotGate.reset();this.inventoryGate.reset();this.equipmentGate.reset();this.playerCraftingGate.reset();this.miningProgressGate.reset();this.chatMessageGate.reset();this.remotePlayerGates.clear();this.itemEntityGates.clear();this.pendingCommands.clear();this.pendingInventoryTransactions.clear();this.pendingEquipmentTransactions.clear();this.pendingPlayerCraftingTransactions.clear();this.commandRequestSeq=0;this.chatSendSeq=0;this.inventoryTransactionRequestSeq=0;this.equipmentTransactionRequestSeq=0;this.playerCraftingTransactionRequestSeq=0;this.inventorySnapshot=null;this.equipmentSnapshot=null;this.playerCraftingSnapshot=null;this.worldEditSync=null;this.worldEditAssembler=null;}
  armHandshakeTimer(){this.clearHandshakeTimer();this.handshakeTimer=this.setTimer(()=>{this.handshakeTimer=null;if(this.state==='handshaking')this.protocolFailure(new Error('multiplayer handshake timed out'),HANDSHAKE_TIMEOUT_CLOSE_CODE,'handshake timeout');},this.handshakeTimeoutMs);}
  connect(url){if(!['idle','closed','rejected','error'].includes(this.state))throw new Error(`cannot connect while websocket client is ${this.state}`);const normalized=normalizeWebSocketUrl(url,{allowInsecure:this.allowInsecure});this.clearHandshakeTimer();this.session=null;this.worldInfo=null;this.packetSeq=0;this.resetRealtimeState();const socket=this.socketFactory(normalized,MULTIPLAYER_SUBPROTOCOL);if(!socket||typeof socket.addEventListener!=='function'||typeof socket.send!=='function'||typeof socket.close!=='function')throw new TypeError('socketFactory must return a WebSocket-compatible object');this.socket=socket;this.setState('connecting');socket.addEventListener('open',()=>this.handleOpen(socket));socket.addEventListener('message',event=>this.handleMessage(socket,event));socket.addEventListener('error',event=>this.handleError(socket,event));socket.addEventListener('close',event=>this.handleClose(socket,event));return normalized;}
  handleOpen(socket){if(socket!==this.socket||this.state!=='connecting')return;if(typeof socket.protocol==='string'&&socket.protocol!==MULTIPLAYER_SUBPROTOCOL){this.protocolFailure(new Error(`server did not negotiate websocket subprotocol ${MULTIPLAYER_SUBPROTOCOL}`),1002,'subprotocol mismatch');return;}this.setState('handshaking');socket.send(JSON.stringify(encodeClientHello()));this.armHandshakeTimer();}

  handleWorldEditSync(raw){if(!this.worldInfo){this.protocolFailure(new Error('world edit sync received before world info'),1002,'world edit before world info');return;}if(this.worldEditSync){this.protocolFailure(new Error('duplicate initial world edit synchronization'),1002,'duplicate world edit sync');return;}if(!this.worldEditAssembler)this.worldEditAssembler=new WorldEditSyncAssembler({session:this.session,worldId:this.worldInfo.worldId});let step;try{step=this.worldEditAssembler.accept(raw);}catch(error){this.protocolFailure(error,1002,'invalid world edit sync');return;}if(!step.complete)return;const sync=Object.freeze({session:this.session,worldId:this.worldInfo.worldId,revision:step.result.revision,edits:step.result.edits});this.worldEditAssembler=null;this.worldEditSync=sync;try{this.onWorldEditSync(sync);}catch(error){this.protocolFailure(error,1011,'world edit sync handler failed');}}
  handleInventorySnapshot(raw){let snapshot;try{snapshot=decodeServerInventorySnapshot(raw,{expectedSession:this.session});}catch(error){this.protocolFailure(error,1002,'invalid inventory snapshot');return;}if(!this.inventoryGate.accept(snapshot.revision)){this.protocolFailure(new Error('stale or duplicate server inventory revision'),1002,'stale inventory snapshot');return;}this.inventorySnapshot=snapshot;try{this.onInventorySnapshot(snapshot);}catch(error){this.protocolFailure(error,1011,'inventory snapshot handler failed');}}
  handleInventoryTransactionResult(raw){let result;try{result=decodeInventoryTransactionResult(raw,{expectedSession:this.session});}catch(error){this.protocolFailure(error,1002,'invalid inventory transaction result');return;}if(!this.pendingInventoryTransactions.delete(result.requestId)){this.protocolFailure(new Error(`unexpected inventory transaction result requestId: ${result.requestId}`),1002,'unexpected inventory transaction result');return;}try{this.onInventoryTransactionResult(result);}catch(error){this.protocolFailure(error,1011,'inventory transaction result handler failed');}}
  handleEquipmentSnapshot(raw){let snapshot;try{snapshot=decodeServerEquipmentSnapshot(raw,{expectedSession:this.session});}catch(error){this.protocolFailure(error,1002,'invalid equipment snapshot');return;}if(!this.equipmentGate.accept(snapshot.revision)){this.protocolFailure(new Error('stale or duplicate server equipment revision'),1002,'stale equipment snapshot');return;}this.equipmentSnapshot=snapshot;try{this.onEquipmentSnapshot(snapshot);}catch(error){this.protocolFailure(error,1011,'equipment snapshot handler failed');}}
  handleEquipmentTransactionResult(raw){let result;try{result=decodeEquipmentTransactionResult(raw,{expectedSession:this.session});}catch(error){this.protocolFailure(error,1002,'invalid equipment transaction result');return;}if(!this.pendingEquipmentTransactions.delete(result.requestId)){this.protocolFailure(new Error(`unexpected equipment transaction result requestId: ${result.requestId}`),1002,'unexpected equipment transaction result');return;}try{this.onEquipmentTransactionResult(result);}catch(error){this.protocolFailure(error,1011,'equipment transaction result handler failed');}}
  handlePlayerCraftingSnapshot(raw){let snapshot;try{snapshot=decodeServerPlayerCraftingSnapshot(raw,{expectedSession:this.session});}catch(error){this.protocolFailure(error,1002,'invalid player crafting snapshot');return;}if(!this.playerCraftingGate.accept(snapshot.revision)){this.protocolFailure(new Error('stale or duplicate server player crafting revision'),1002,'stale player crafting snapshot');return;}this.playerCraftingSnapshot=snapshot;try{this.onPlayerCraftingSnapshot(snapshot);}catch(error){this.protocolFailure(error,1011,'player crafting snapshot handler failed');}}
  handlePlayerCraftingTransactionResult(raw){let result;try{result=decodePlayerCraftingTransactionResult(raw,{expectedSession:this.session});}catch(error){this.protocolFailure(error,1002,'invalid player crafting transaction result');return;}if(!this.pendingPlayerCraftingTransactions.delete(result.requestId)){this.protocolFailure(new Error(`unexpected player crafting transaction result requestId: ${result.requestId}`),1002,'unexpected player crafting transaction result');return;}try{this.onPlayerCraftingTransactionResult(result);}catch(error){this.protocolFailure(error,1011,'player crafting transaction result handler failed');}}
  handleMiningProgress(raw){let message;try{message=decodeMiningProgress(raw,{expectedSession:this.session});}catch(error){this.protocolFailure(error,1002,'invalid mining progress');return;}if(!this.miningProgressGate.accept(message.tick)){this.protocolFailure(new Error('stale or duplicate mining progress tick'),1002,'stale mining progress');return;}try{this.onMiningProgress(message);}catch(error){this.protocolFailure(error,1011,'mining progress handler failed');}}
  handleCommandResult(raw){let result;try{result=decodeMultiplayerCommandResult(raw,{expectedSession:this.session});}catch(error){this.protocolFailure(error,1002,'invalid command result');return;}if(!this.pendingCommands.delete(result.requestId)){this.protocolFailure(new Error(`unexpected multiplayer command result requestId: ${result.requestId}`),1002,'unexpected command result');return;}try{this.onCommandResult(result);}catch(error){this.protocolFailure(error,1011,'command result handler failed');}}
  handleChatMessage(raw){let message;try{message=decodeMultiplayerChatMessage(raw);}catch(error){this.protocolFailure(error,1002,'invalid chat message');return;}if(!this.chatMessageGate.accept(message.messageSeq)){this.protocolFailure(new Error('stale or duplicate multiplayer chat message sequence'),1002,'stale chat message');return;}try{this.onChatMessage(message);}catch(error){this.protocolFailure(error,1011,'chat message handler failed');}}
  handleRemotePlayerMessage(raw){let message;try{message=decodeRemotePlayerReplication(raw);}catch(error){this.protocolFailure(error,1002,'invalid remote player replication');return;}if(message.kind===REMOTE_PLAYER_SPAWN_KIND){if(this.remotePlayerGates.has(message.playerId)){this.protocolFailure(new Error(`duplicate remote player spawn: ${message.playerId}`),1002,'duplicate remote player spawn');return;}const gate=new NetworkSequenceGate();gate.accept(message.tick);this.remotePlayerGates.set(message.playerId,gate);try{this.onRemotePlayerSpawn(message);}catch(error){this.protocolFailure(error,1011,'remote player spawn handler failed');}return;}const gate=this.remotePlayerGates.get(message.playerId);if(!gate){this.protocolFailure(new Error(`unknown remote player: ${message.playerId}`),1002,'unknown remote player');return;}if(message.kind===REMOTE_PLAYER_SNAPSHOT_KIND){if(!gate.accept(message.tick)){this.protocolFailure(new Error(`stale or duplicate remote player tick: ${message.playerId}`),1002,'stale remote player snapshot');return;}try{this.onRemotePlayerSnapshot(message);}catch(error){this.protocolFailure(error,1011,'remote player snapshot handler failed');}return;}if(message.kind===REMOTE_PLAYER_DESPAWN_KIND){this.remotePlayerGates.delete(message.playerId);try{this.onRemotePlayerDespawn(message);}catch(error){this.protocolFailure(error,1011,'remote player despawn handler failed');}}
  }
  handleItemEntityMessage(raw){let message;try{message=decodeItemEntityReplication(raw);}catch(error){this.protocolFailure(error,1002,'invalid item entity replication');return;}if(message.kind===ITEM_ENTITY_SPAWN_KIND){if(this.itemEntityGates.has(message.entityId)){this.protocolFailure(new Error(`duplicate item entity spawn: ${message.entityId}`),1002,'duplicate item entity spawn');return;}const gate=new NetworkSequenceGate();gate.accept(message.revision);this.itemEntityGates.set(message.entityId,gate);try{this.onItemEntitySpawn(message);}catch(error){this.protocolFailure(error,1011,'item entity spawn handler failed');}return;}const gate=this.itemEntityGates.get(message.entityId);if(!gate){this.protocolFailure(new Error(`unknown item entity: ${message.entityId}`),1002,'unknown item entity');return;}if(!gate.accept(message.revision)){this.protocolFailure(new Error(`stale or duplicate item entity revision: ${message.entityId}`),1002,'stale item entity revision');return;}if(message.kind===ITEM_ENTITY_SNAPSHOT_KIND){try{this.onItemEntitySnapshot(message);}catch(error){this.protocolFailure(error,1011,'item entity snapshot handler failed');}return;}if(message.kind===ITEM_ENTITY_DESPAWN_KIND){this.itemEntityGates.delete(message.entityId);try{this.onItemEntityDespawn(message);}catch(error){this.protocolFailure(error,1011,'item entity despawn handler failed');}}
  }

  handleMessage(socket,event){if(socket!==this.socket)return;let raw;try{raw=parseJsonServerMessage(event?.data);}catch(error){this.protocolFailure(error,1002,'invalid server message');return;}if(this.state==='handshaking'){let message;try{message=decodeServerHandshake(raw);}catch(error){this.protocolFailure(error,1002,'invalid handshake');return;}this.clearHandshakeTimer();if(message.kind==='reject'){this.session=null;this.worldInfo=null;this.resetRealtimeState();this.setState('rejected',message.code);socket.close(1000,'server rejected connection');return;}this.session=message.session;this.worldInfo=null;this.packetSeq=0;this.resetRealtimeState();this.setState('ready',message.session);return;}
    if(this.state==='ready'){
      if(raw.kind===MULTIPLAYER_COMMAND_RESULT_KIND){this.handleCommandResult(raw);return;}
      if(raw.kind===MULTIPLAYER_CHAT_MESSAGE_KIND){this.handleChatMessage(raw);return;}
      if(raw.kind===INVENTORY_TRANSACTION_RESULT_KIND){this.handleInventoryTransactionResult(raw);return;}
      if(raw.kind===EQUIPMENT_TRANSACTION_RESULT_KIND){this.handleEquipmentTransactionResult(raw);return;}
      if(raw.kind===PLAYER_CRAFTING_TRANSACTION_RESULT_KIND){this.handlePlayerCraftingTransactionResult(raw);return;}
      if(raw.kind===SERVER_WORLD_INFO_KIND){if(this.worldInfo!==null){this.protocolFailure(new Error('duplicate server world info'),1002,'duplicate world info');return;}let info;try{info=decodeServerWorldInfo(raw,{expectedSession:this.session});}catch(error){this.protocolFailure(error,1002,'invalid world info');return;}this.worldInfo=info;try{this.onWorldInfo(info);}catch(error){this.protocolFailure(error,1011,'world info handler failed');}return;}
      if(isInitialWorldEditKind(raw.kind)){this.handleWorldEditSync(raw);return;}
      if(raw.kind===SERVER_INVENTORY_SNAPSHOT_KIND){this.handleInventorySnapshot(raw);return;}
      if(raw.kind===SERVER_EQUIPMENT_SNAPSHOT_KIND){this.handleEquipmentSnapshot(raw);return;}
      if(raw.kind===SERVER_PLAYER_CRAFTING_SNAPSHOT_KIND){this.handlePlayerCraftingSnapshot(raw);return;}
      if(raw.kind==='player-snapshot'){let snapshot;try{snapshot=decodeServerPlayerSnapshot(raw,{expectedSession:this.session});}catch(error){this.protocolFailure(error,1002,'invalid player snapshot');return;}if(!this.snapshotGate.accept(snapshot.tick)){this.protocolFailure(new Error('stale or duplicate server player snapshot tick'),1002,'stale player snapshot');return;}try{this.onPlayerSnapshot(snapshot);}catch(error){this.protocolFailure(error,1011,'player snapshot handler failed');}return;}
      if(raw.kind===MINING_PROGRESS_KIND){this.handleMiningProgress(raw);return;}
      if(raw.kind===REMOTE_PLAYER_SPAWN_KIND||raw.kind===REMOTE_PLAYER_SNAPSHOT_KIND||raw.kind===REMOTE_PLAYER_DESPAWN_KIND){this.handleRemotePlayerMessage(raw);return;}
      if(raw.kind===ITEM_ENTITY_SPAWN_KIND||raw.kind===ITEM_ENTITY_SNAPSHOT_KIND||raw.kind===ITEM_ENTITY_DESPAWN_KIND){this.handleItemEntityMessage(raw);return;}
      this.protocolFailure(new Error(`unsupported server realtime message kind: ${raw.kind}`),1002,'unsupported realtime message');return;
    }
    this.protocolFailure(new Error(`unexpected server message while websocket client is ${this.state}`),1002,'unexpected message');
  }

  handleError(socket,event){if(socket!==this.socket)return;this.clearHandshakeTimer();this.session=null;this.worldInfo=null;this.resetRealtimeState();this.setState('error',event||null);}
  handleClose(socket,event){if(socket!==this.socket)return;this.clearHandshakeTimer();this.session=null;this.worldInfo=null;this.resetRealtimeState();if(this.state!=='rejected'&&this.state!=='error')this.setState('closed',event||null);}
  protocolFailure(error,code=1002,reason='protocol error'){this.clearHandshakeTimer();this.session=null;this.worldInfo=null;this.resetRealtimeState();this.onProtocolError(error);const socket=this.socket;this.setState('error',error?.message||String(error));if(socket)try{socket.close(code,reason);}catch{}}
  sendInput(kind,payload){if(this.state!=='ready'||!this.session||!this.socket)throw new Error('websocket client is not ready');if(this.socket.readyState!==undefined&&this.socket.readyState!==1)throw new Error('websocket transport is not open');const envelope=encodeClientInputEnvelope({session:this.session,packetSeq:this.packetSeq,kind,payload});this.socket.send(JSON.stringify(envelope));this.packetSeq=nextNetworkSequence(this.packetSeq);return envelope;}
  sendCommand(text){if(this.state!=='ready'||!this.session||!this.socket)throw new Error('websocket client is not ready');if(this.socket.readyState!==undefined&&this.socket.readyState!==1)throw new Error('websocket transport is not open');if(this.pendingCommands.size>=MAX_PENDING_MULTIPLAYER_COMMANDS)throw new Error('too many multiplayer commands are awaiting server results');const request=encodeMultiplayerCommandRequest({session:this.session,requestId:this.commandRequestSeq,text});this.socket.send(JSON.stringify(request));this.pendingCommands.add(request.requestId);this.commandRequestSeq=nextNetworkSequence(this.commandRequestSeq);return request;}
  sendChat(text){if(this.state!=='ready'||!this.session||!this.socket)throw new Error('websocket client is not ready');if(this.socket.readyState!==undefined&&this.socket.readyState!==1)throw new Error('websocket transport is not open');const message=encodeMultiplayerChatSend({session:this.session,clientSeq:this.chatSendSeq,text});this.socket.send(JSON.stringify(message));this.chatSendSeq=nextNetworkSequence(this.chatSendSeq);return message;}
  sendInventoryTransaction(action,expectedRevision){if(this.state!=='ready'||!this.session||!this.socket)throw new Error('websocket client is not ready');if(this.socket.readyState!==undefined&&this.socket.readyState!==1)throw new Error('websocket transport is not open');if(this.pendingInventoryTransactions.size>=MAX_PENDING_INVENTORY_TRANSACTIONS)throw new Error('an inventory transaction is already awaiting the server');const request=encodeInventoryTransactionRequest({session:this.session,requestId:this.inventoryTransactionRequestSeq,expectedRevision,action});this.socket.send(JSON.stringify(request));this.pendingInventoryTransactions.add(request.requestId);this.inventoryTransactionRequestSeq=nextNetworkSequence(this.inventoryTransactionRequestSeq);return request;}
  sendEquipmentTransaction({slot,button},expectedInventoryRevision,expectedEquipmentRevision){if(this.state!=='ready'||!this.session||!this.socket)throw new Error('websocket client is not ready');if(this.socket.readyState!==undefined&&this.socket.readyState!==1)throw new Error('websocket transport is not open');if(this.pendingEquipmentTransactions.size>=MAX_PENDING_EQUIPMENT_TRANSACTIONS)throw new Error('an equipment transaction is already awaiting the server');const request=encodeEquipmentTransactionRequest({session:this.session,requestId:this.equipmentTransactionRequestSeq,expectedInventoryRevision,expectedEquipmentRevision,slot,button});this.socket.send(JSON.stringify(request));this.pendingEquipmentTransactions.add(request.requestId);this.equipmentTransactionRequestSeq=nextNetworkSequence(this.equipmentTransactionRequestSeq);return request;}
  sendPlayerCraftingTransaction(action,expectedInventoryRevision,expectedCraftingRevision){if(this.state!=='ready'||!this.session||!this.socket)throw new Error('websocket client is not ready');if(this.socket.readyState!==undefined&&this.socket.readyState!==1)throw new Error('websocket transport is not open');if(this.pendingPlayerCraftingTransactions.size>=MAX_PENDING_PLAYER_CRAFTING_TRANSACTIONS)throw new Error('a player crafting transaction is already awaiting the server');const request=encodePlayerCraftingTransactionRequest({session:this.session,requestId:this.playerCraftingTransactionRequestSeq,expectedInventoryRevision,expectedCraftingRevision,action});this.socket.send(JSON.stringify(request));this.pendingPlayerCraftingTransactions.add(request.requestId);this.playerCraftingTransactionRequestSeq=nextNetworkSequence(this.playerCraftingTransactionRequestSeq);return request;}
  close(code=1000,reason='client closed connection'){this.clearHandshakeTimer();this.session=null;this.worldInfo=null;this.resetRealtimeState();const socket=this.socket;this.socket=null;if(socket)socket.close(code,reason);this.setState('closed',{code,reason});}
}
